// VoiceState.swift — Observable state model for Voice Bar.
//
// Single source of truth for all UI state. Maps socket protocol events
// (from VoiceLayer MCP server) to SwiftUI-friendly properties.
// VoiceMode values must match socket-protocol.ts VoiceLayerState.

import AppKit
import Foundation
import Observation
import SwiftUI

private extension NSPasteboard.PasteboardType {
    static let voiceBarTransient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let voiceBarAutoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

// MARK: - Voice mode enumeration

public enum VoiceMode: String, CaseIterable {
    case idle
    case speaking
    case recording
    case transcribing
    case error
    case disconnected
}

public struct QueueItemState: Equatable {
    public var text: String
    public var voice: String
    public var priority: String
    public var isCurrent: Bool
    public var progress: Double
}

public enum CommandModePhase: String, Equatable {
    case listening
    case capturing
    case applying
    case fallback
    case done
    case error
}

public struct CommandModeState: Equatable {
    public var phase: CommandModePhase
    public var operation: String
    public var prompt: String?
}

public struct ClipMarkerState: Equatable {
    public var id: String
    public var label: String
    public var source: String
    public var status: String
}

public struct STTPolishDegradation: Equatable {
    public var reason: String
    public var hint: String
}

public struct PasteboardSnapshot: Equatable {
    public var changeCount: Int
    public var items: [[String: Data]]
}

public struct RecentTranscriptionEntry: Codable, Equatable {
    public var text: String
    public var recordingPath: String?

    public init(text: String, recordingPath: String? = nil) {
        self.text = text
        self.recordingPath = recordingPath
    }
}

private enum VoicePasteOutcome: Equatable {
    case insertedAtCursor
    case pasted
    case failed(String)
}

private struct HistoryRetranscriptionRequest {
    private struct Intent {
        let id: String
        let path: String
    }

    private var activePath: String?
    private var pendingIntent: Intent?
    private var suppressedPaths = Set<String>()

    var isPending: Bool {
        activePath != nil
    }

    var activeRecordingPath: String? {
        activePath
    }

    mutating func begin(path: String, intentID id: String) -> Bool {
        guard activePath == nil, pendingIntent == nil else { return false }
        activePath = path
        pendingIntent = Intent(id: id, path: path)
        suppressedPaths.insert(path)
        return true
    }

    func suppressesPaste(for path: String) -> Bool {
        activePath == path || suppressedPaths.contains(path)
    }

    func matchesIntent(id: String?) -> Bool {
        pendingIntent?.id == id
    }

    func currentPath() -> String? {
        activePath ?? pendingIntent?.path
    }

    mutating func acknowledgeIntent() {
        pendingIntent = nil
    }

    mutating func clear(removeSuppression: Bool) {
        let path = currentPath()
        if removeSuppression, let path {
            suppressedPaths.remove(path)
        }
        activePath = nil
        pendingIntent = nil
    }

    mutating func finish(path: String) {
        suppressedPaths.remove(path)
        if activePath == path {
            activePath = nil
        }
        if pendingIntent?.path == path {
            pendingIntent = nil
        }
    }

    mutating func reject(path: String?) {
        if let path {
            suppressedPaths.remove(path)
            if activePath == path {
                activePath = nil
            }
        } else {
            activePath = nil
        }
        pendingIntent = nil
    }
}

// MARK: - Observable state

@Observable
public final class VoiceState {
    private static let maxRecentTranscriptions = 8
    private static let recentTranscriptionsDefaultsKey = "VoiceBar.recentTranscriptions"
    private static let recentTranscriptionEntriesDefaultsKey = "VoiceBar.recentTranscriptionEntries.v1"
    private static let maxVocabularyTerms = 512
    private static let maxVocabularyAliases = 512

    /// UI-bound properties -- all mutations must happen on the main thread.
    public var mode: VoiceMode = .idle {
        didSet { notifyPanelLayoutChangedIfNeeded(oldValue != mode) }
    }

    public var statusText: String = ""
    public var transcript: String = ""
    public private(set) var lastTranscriptionPolished: Bool?
    public private(set) var lastTranscriptionPolishReason: String?
    public var speechDetected: Bool = false
    public var isConnected: Bool = false
    public var errorMessage: String?
    public private(set) var polishDegradation: STTPolishDegradation?
    public private(set) var polishMenuSignalPending = false
    private var dismissedPolishDegradation: STTPolishDegradation?
    public var transcribingStatusText: String? {
        didSet { notifyPanelLayoutChangedIfNeeded(oldValue != transcribingStatusText) }
    }

    // Recording metadata
    public var recordingMode: String? // "vad" or "ptt"
    public var silenceMode: String? // "quick" | "standard" | "thoughtful"

    /// Brief confirmation text shown after paste (e.g., "Pasted!").
    public var confirmationText: String? {
        didSet { notifyPanelLayoutChangedIfNeeded(oldValue != confirmationText) }
    }

    /// Keeps the post-record paste flow in one fixed panel envelope so loading,
    /// success, and failure substates crossfade instead of re-centering.
    public var keepsPasteFlowEnvelope: Bool = false {
        didSet { notifyPanelLayoutChangedIfNeeded(oldValue != keepsPasteFlowEnvelope) }
    }

    /// Real-time audio level (0.0–1.0) from RMS events.
    public var audioLevel: Double?
    private var socketAudioLevel: Double?
    private var localRecordingLevel: Double?
    private var recordCommandUptimeMs: Int?
    private var recordingStateUptimeMs: Int?
    private var didLogFirstRecordingAudioLevel = false
    public var recordingTimingClock: () -> TimeInterval = {
        ProcessInfo.processInfo.systemUptime
    }

    /// Word boundary timestamps from TTS engine (ms offsets from audio start).
    public var wordBoundaries: [(offsetMs: Int, durationMs: Int, text: String)] = []

    /// Whether the last completed action was TTS playback (replay is valid).
    /// Set true when speaking state arrives, false when recording starts.
    public var canReplay: Bool = false

    /// Recent transcription history with the newest item first.
    public var recentTranscriptionEntries: [RecentTranscriptionEntry] = [] {
        didSet {
            recentTranscriptions = recentTranscriptionEntries.map(\.text)
            notifyPanelLayoutChangedIfNeeded(oldValue.isEmpty != recentTranscriptionEntries.isEmpty)
        }
    }

    /// Recent transcription text projection kept for older menu and hotkey paths.
    public var recentTranscriptions: [String] = [] {
        didSet { notifyPanelLayoutChangedIfNeeded(oldValue.isEmpty != recentTranscriptions.isEmpty) }
    }

    /// Active STT vocabulary hints loaded from the daemon snapshot.
    public var transcriptionVocabularyTerms: [String] = [] {
        didSet { notifyPanelLayoutChangedIfNeeded(oldValue.isEmpty != transcriptionVocabularyTerms.isEmpty) }
    }

    public var transcriptionVocabularyAliases: [STTVocabularyAliasPreview] = [] {
        didSet { notifyPanelLayoutChangedIfNeeded(oldValue.isEmpty != transcriptionVocabularyAliases.isEmpty) }
    }

    /// Latest completed transcript safe for re-paste/copy actions.
    public var latestReusableTranscript: String {
        recentTranscriptions.first?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
    }

    /// Total queued + currently playing TTS items.
    public var queueDepth: Int = 0 {
        didSet { notifyPanelLayoutChangedIfNeeded(oldValue != queueDepth) }
    }

    public var queueItems: [QueueItemState] = [] {
        didSet { notifyPanelLayoutChangedIfNeeded(oldValue.count != queueItems.count) }
    }

    public var commandModeState: CommandModeState? {
        didSet { notifyPanelLayoutChangedIfNeeded(oldValue != commandModeState) }
    }

    public var activeClipMarker: ClipMarkerState? {
        didSet { notifyPanelLayoutChangedIfNeeded(oldValue != activeClipMarker) }
    }

    /// Global hotkey availability and live gesture hint state.
    public var hotkeyEnabled: Bool = false
    public var hotkeyPhase: HotkeyPhase = .idle {
        didSet { notifyPanelLayoutChangedIfNeeded(oldValue != hotkeyPhase) }
    }

    /// Whether the pill is collapsed (idle for too long).
    public var isCollapsed: Bool = false {
        didSet { notifyPanelLayoutChangedIfNeeded(oldValue != isCollapsed) }
    }

    /// Whether the mouse is hovering over the pill.
    public var isHovering: Bool = false

    /// Timer for idle collapse.
    private var collapseTimer: Task<Void, Never>?
    private var modalInteractionDepth = 0
    public var idleCollapseDelay: TimeInterval = Theme.collapseDelay

    /// Tracks the last user intent sent to the daemon until the matching ack returns.
    public var pendingIntent: PendingIntent?

    /// Safety timeout for barInitiatedRecording — prevents stuck state.
    private var barInitiatedTimeout: Task<Void, Never>?
    private var transcriptionTimeoutTask: Task<Void, Never>?
    private var recordingIdleCleanupTask: Task<Void, Never>?
    private var deferredFinalTranscriptionTask: Task<Void, Never>?
    private var deferredFinalTranscriptionRecordingPath: String?
    private var recordStartAckTimeoutTask: Task<Void, Never>?
    private var recordStartLateRecoveryTask: Task<Void, Never>?
    private var transcribingStartedAt: Date?
    private var pendingRecordingIdleAfterFinal = false
    private var pendingIdleAfterAutoPasteCompletion = false
    private var pendingRecoveredTranscriptionPaste = false
    private var historyRetranscriptionRequest = HistoryRetranscriptionRequest()
    private var canRecoverLateRecordStart = false

    public var isHistoryRetranscriptionPending: Bool {
        historyRetranscriptionRequest.isPending
    }

    public var activeHistoryRetranscriptionPath: String? {
        historyRetranscriptionRequest.activeRecordingPath
    }

    /// Whether the current recording was initiated from the Voice Bar (vs MCP).
    /// When true, transcription result is auto-pasted at the cursor.
    /// Cleared after transcription, recording-idle cleanup, cancel, disconnect, or a rejected record ack.
    /// Never cleared by idle/error alone — those are ambiguous with multiple MCP clients.
    private var barInitiatedRecording = false

    /// The app that was frontmost when bar-initiated recording started.
    private var frontmostAppOnRecordStart: NSRunningApplication?
    private var recordStartInsertionHandler: ((String) -> Bool)?

    /// The most recent app we pasted into. Reused for Shift+F5 re-paste.
    private var lastPasteTargetApp: NSRunningApplication?
    private var settingsHistoryPasteTargetApp: NSRunningApplication?
    private var settingsHistoryInsertionHandler: ((String) -> Bool)?

    /// Test seam for paste side effects. When set, bypasses system paste.
    public var pasteHandler: ((String) -> Bool)?
    public var commandModeApplyHandler: ((String) -> CommandModeApplyResult)?

    /// Delay before sending Cmd+V after activating the target app.
    public var pasteConfirmationDelay: TimeInterval = 0.25
    public var pasteboardRestoreDelay: TimeInterval = 0.5

    /// Test seam for delayed paste scheduling.
    public var pasteScheduler: (TimeInterval, @escaping () -> Void) -> Void = { delay, block in
        DispatchQueue.main.asyncAfter(deadline: .now() + delay, execute: block)
    }

    /// Test seam for re-activating the target app before paste.
    public var targetAppActivator: (NSRunningApplication) -> Void = { app in
        app.activate()
    }

    /// Test seam for the frontmost app at record/paste time.
    public var frontmostAppProvider: () -> NSRunningApplication? = {
        NSWorkspace.shared.frontmostApplication
    }

    /// Test seam for the final Cmd+V event posting.
    public var simulatedPasteHandler: () -> Bool = { false }

    /// Test seam for Accessibility permission checks.
    public var accessibilityTrustChecker: (_ prompt: Bool) -> Bool = { _ in false }

    /// Test seam for capturing a direct insertion closure tied to the focused input.
    public var dictationInsertionHandlerProvider: () -> ((String) -> Bool)? = { nil }

    /// Test seam for clipboard writes used by fallback paste.
    public var pasteboardWriter: (String) -> Void = { string in
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(string, forType: .string)
        pasteboard.setData(Data(), forType: .voiceBarTransient)
        pasteboard.setData(Data(), forType: .voiceBarAutoGenerated)
    }

    public var pasteboardStringProvider: () -> String? = {
        NSPasteboard.general.string(forType: .string)
    }

    public var pasteboardSnapshotter: () -> PasteboardSnapshot? = {
        VoiceState.capturePasteboardSnapshot()
    }

    public var pasteboardSnapshotRestorer: (PasteboardSnapshot) -> Void = { snapshot in
        VoiceState.restorePasteboardSnapshot(snapshot)
    }

    public var pasteboardChangeCountProvider: () -> Int = {
        NSPasteboard.general.changeCount
    }

    public var currentDateProvider: () -> Date = {
        Date()
    }

    private let recentTranscriptionsSaver: ([String]) -> Void
    private let recentTranscriptionEntriesSaver: ([RecentTranscriptionEntry]) -> Void
    private let transcriptionVocabularyLoader: () -> [String]
    private let transcriptionVocabularyAliasLoader: () -> [STTVocabularyAliasPreview]

    /// Transport-layer hook injected by AppDelegate.
    /// BarView calls stop()/toggle()/replay() which forward through this closure.
    public var sendCommand: (([String: Any]) -> Void)?

    /// Callback when the pill's rendered size changes — used to resize the NSPanel.
    public var onPillSizeChange: ((CGSize) -> Void)?

    /// Callback when socket connection state changes — used to suspend/resume polling.
    public var onConnectionChange: ((Bool) -> Void)?

    /// Callback when voice mode changes — used to lock/unlock pill dragging.
    public var onModeChange: ((VoiceMode) -> Void)?
    public var onPanelLayoutChange: (() -> Void)?
    public var onHistoryArchiveChange: (() -> Void)?
    public var onAckEvent: ((SocketAckEvent) -> Void)?
    public var onPolishStatusChange: (() -> Void)?
    public var diagnosticLogger: ((String, [String: String]) -> Void)?
    public var controlLayerEventWriter: (String, [String: String]) -> Void = { event, details in
        ControlLayerJournal.append(type: "voicebar.\(event)", payload: details)
    }

    public var transcriptionTimeout: Duration = .seconds(30)
    public var barInitiatedTranscriptionTimeout: Duration = .seconds(900)
    public var barInitiatedSafetyTimeout: Duration = .seconds(3660)
    public var recordStartAckTimeout: Duration = .seconds(2)
    public var recordStartLateRecoveryWindow: Duration = .seconds(10)
    public var recordingIdleFinalTranscriptGrace: Duration = .seconds(2)
    public var minimumTranscribingDisplayDuration: TimeInterval = 0.65

    public init(
        recentTranscriptionsLoader: @escaping () -> [String] = {
            VoiceState.loadRecentTranscriptions()
        },
        recentTranscriptionsSaver: @escaping ([String]) -> Void = {
            VoiceState.saveRecentTranscriptions($0)
        },
        recentTranscriptionEntriesLoader: @escaping () -> [RecentTranscriptionEntry] = {
            VoiceState.loadRecentTranscriptionEntries()
        },
        recentTranscriptionEntriesSaver: @escaping ([RecentTranscriptionEntry]) -> Void = {
            VoiceState.saveRecentTranscriptionEntries($0)
        },
        transcriptionVocabularyLoader: @escaping () -> [String] = { [] },
        transcriptionVocabularyAliasLoader: @escaping () -> [STTVocabularyAliasPreview] = { [] }
    ) {
        self.recentTranscriptionsSaver = recentTranscriptionsSaver
        self.recentTranscriptionEntriesSaver = recentTranscriptionEntriesSaver
        self.transcriptionVocabularyLoader = transcriptionVocabularyLoader
        self.transcriptionVocabularyAliasLoader = transcriptionVocabularyAliasLoader
        recentTranscriptionEntries = Self.normalizeRecentTranscriptionEntries(
            recentTranscriptionEntriesLoader(),
            fallbackTexts: recentTranscriptionsLoader()
        )
        recentTranscriptions = recentTranscriptionEntries.map(\.text)
        transcriptionVocabularyTerms = Self.normalizeVocabularyTerms(transcriptionVocabularyLoader())
        transcriptionVocabularyAliases = Self.normalizeVocabularyAliases(
            transcriptionVocabularyAliasLoader()
        )
    }

    // MARK: - Commands

    public func stop() {
        let shouldShowTranscribing = mode == .recording
        sendIntent(command: .stop, payload: ["cmd": "stop"])
        if shouldShowTranscribing {
            enterTranscribingMode()
        }
    }

    public func dismissError() {
        pendingIntent = nil
        errorMessage = nil
        cancelDeferredFinalTranscription()
        pendingRecordingIdleAfterFinal = false
        pendingIdleAfterAutoPasteCompletion = false
        pendingRecoveredTranscriptionPaste = false
        clearHistoryRetranscriptionRequest(removeSuppression: true)
        clearRecordStartLateRecovery(clearPasteTarget: false)
        keepsPasteFlowEnvelope = false
        transcribingStartedAt = nil
        transcribingStatusText = nil
        frontmostAppOnRecordStart = nil
        recordStartInsertionHandler = nil
        speechDetected = false
        recordingMode = nil
        silenceMode = nil
        resetAudioLevels()

        if isConnected {
            mode = .idle
            onModeChange?(.idle)
            startCollapseTimer()
        } else {
            mode = .disconnected
            onModeChange?(.disconnected)
            collapseTimer?.cancel()
            isCollapsed = false
        }
    }

    public func cancel() {
        barInitiatedRecording = false
        barInitiatedTimeout?.cancel()
        transcriptionTimeoutTask?.cancel()
        recordingIdleCleanupTask?.cancel()
        cancelDeferredFinalTranscription()
        recordStartAckTimeoutTask?.cancel()
        pendingRecordingIdleAfterFinal = false
        pendingIdleAfterAutoPasteCompletion = false
        pendingRecoveredTranscriptionPaste = false
        clearHistoryRetranscriptionRequest(removeSuppression: true)
        clearRecordStartLateRecovery(clearPasteTarget: false)
        keepsPasteFlowEnvelope = false
        transcribingStartedAt = nil
        transcribingStatusText = nil
        frontmostAppOnRecordStart = nil
        recordStartInsertionHandler = nil
        speechDetected = false
        resetAudioLevels()
        hotkeyPhase = .idle
        statusText = ""
        sendIntent(command: .cancel, payload: ["cmd": "cancel"])
        if mode == .recording || mode == .transcribing || mode == .speaking {
            mode = isConnected ? .idle : .disconnected
            onModeChange?(mode)
            if mode == .idle {
                startCollapseTimer()
            } else {
                collapseTimer?.cancel()
                isCollapsed = false
            }
        }
    }

    public func toggle(scope: String = "all", enabled: Bool) {
        sendIntent(
            command: .toggle,
            payload: ["cmd": "toggle", "scope": scope, "enabled": enabled]
        )
    }

    public func replay() {
        sendIntent(command: .replay, payload: ["cmd": "replay"])
    }

    public func retranscribeLastCapture() {
        guard !pendingRecoveredTranscriptionPaste else { return }
        pendingRecoveredTranscriptionPaste = true
        sendIntent(
            command: .retranscribeLast,
            payload: ["cmd": "retranscribe_last"]
        )
    }

    public func retranscribeHistoryEntry(recordingPath: String) {
        let trimmedPath = recordingPath.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedPath.isEmpty else { return }
        let id = UUID().uuidString
        guard historyRetranscriptionRequest.begin(path: trimmedPath, intentID: id) else { return }
        sendCommand?([
            "cmd": "retranscribe_recording",
            "audio_path": trimmedPath,
            "id": id,
        ])
    }

    public func snooze() {
        switch mode {
        case .recording, .transcribing:
            sendIntent(command: .cancel, payload: ["cmd": "cancel"], trackPending: false)
        case .speaking:
            sendIntent(command: .stop, payload: ["cmd": "stop"], trackPending: false)
        default:
            break
        }
        barInitiatedRecording = false
        barInitiatedTimeout?.cancel()
        transcriptionTimeoutTask?.cancel()
        recordingIdleCleanupTask?.cancel()
        cancelDeferredFinalTranscription()
        recordStartAckTimeoutTask?.cancel()
        pendingRecordingIdleAfterFinal = false
        pendingIdleAfterAutoPasteCompletion = false
        pendingRecoveredTranscriptionPaste = false
        clearHistoryRetranscriptionRequest(removeSuppression: true)
        clearRecordStartLateRecovery(clearPasteTarget: false)
        keepsPasteFlowEnvelope = true
        transcribingStartedAt = nil
        transcribingStatusText = nil
        frontmostAppOnRecordStart = nil
        recordStartInsertionHandler = nil
        speechDetected = false
        resetAudioLevels()
        hotkeyPhase = .idle
        mode = .disconnected
        onModeChange?(.disconnected)
        collapseTimer?.cancel()
        isCollapsed = false
    }

    public func unsnooze() {
        guard mode == .disconnected else { return }
        keepsPasteFlowEnvelope = false
        isCollapsed = false
        mode = .idle
        onModeChange?(.idle)
        startCollapseTimer()
    }

    public func setLocalRecordingLevel(_ level: Double?) {
        guard mode == .recording else { return }
        localRecordingLevel = level.map { min(1, max(0, $0)) }
        refreshAudioLevel()
    }

    /// Paste the most recent transcript into the current target app again.
    public func repasteLastTranscript(source: String = "unknown") {
        repasteTranscript(latestReusableTranscript, source: source)
    }

    /// Paste a specific transcript from history into the current target app.
    public func repasteTranscript(_ text: String, source: String = "unknown") {
        let reusableText = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !reusableText.isEmpty else { return }
        let usesSettingsHistoryTarget = source == "settings_history"
        logDiagnostic("repaste_requested", details: [
            "transcriptLength": String(reusableText.count),
            "hasCapturedInsertion": boolString(recordStartInsertionHandler != nil),
            "source": source,
        ])
        pasteTranscript(
            reusableText,
            for: resolvedPasteTarget(
                forRepaste: true,
                useSettingsHistoryTarget: usesSettingsHistoryTarget
            ),
            plan: .repaste,
            allowAXInsertion: usesSettingsHistoryTarget
        )
    }

    public func captureSettingsHistoryPasteTarget() {
        guard let front = frontmostAppProvider(),
              front.bundleIdentifier != Bundle.main.bundleIdentifier
        else { return }
        settingsHistoryPasteTargetApp = front
        settingsHistoryInsertionHandler = dictationInsertionHandlerProvider()
    }

    public func copyLastTranscript() {
        copyTranscript(latestReusableTranscript)
    }

    public func copyTranscript(_ text: String) {
        let reusableText = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !reusableText.isEmpty else { return }
        pasteboardWriter(reusableText)
        logDiagnostic("copy_transcript", details: [
            "transcriptLength": String(reusableText.count),
        ])
        showConfirmation("Copied")
    }

    public func addVocabularyAlias(
        correct: String,
        wrong: String
    ) {
        let draft = STTVocabularyDraft(
            correct: correct,
            wrong: wrong
        )
        guard let payload = draft.addAliasPayload() else { return }
        sendCommand?(payload)
        sendCommand?(STTVocabularyCommandPayload.list())
    }

    public func removeVocabularyAlias(_ alias: STTVocabularyAliasPreview) {
        sendCommand?(STTVocabularyCommandPayload.removeAlias(alias))
        sendCommand?(STTVocabularyCommandPayload.list())
    }

    public func addVocabularyPromptTerm(_ term: String) {
        let trimmed = term.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        sendCommand?(STTVocabularyCommandPayload.addTerm(trimmed))
        sendCommand?(STTVocabularyCommandPayload.list())
    }

    public func removeVocabularyPromptTerm(_ term: String) {
        let trimmed = term.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        sendCommand?(STTVocabularyCommandPayload.removeTerm(trimmed))
        sendCommand?(STTVocabularyCommandPayload.list())
    }

    /// Start recording from the Voice Bar. Captures the frontmost app for paste-on-stop.
    public func record(pressToTalk: Bool = false) {
        guard mode == .idle || mode == .error else { return }
        guard pendingIntent?.command != .record else { return }
        let commandUptimeMs = currentRecordingUptimeMs()
        recordCommandUptimeMs = commandUptimeMs
        recordingStateUptimeMs = nil
        didLogFirstRecordingAudioLevel = false
        cancelDeferredFinalTranscriptionUnlessHistoryRetranscription()
        pendingRecordingIdleAfterFinal = false
        pendingIdleAfterAutoPasteCompletion = false
        pendingRecoveredTranscriptionPaste = false
        clearHistoryRetranscriptionRequest(removeSuppression: false)
        clearRecordStartLateRecovery(clearPasteTarget: true)
        keepsPasteFlowEnvelope = false
        transcribingStartedAt = nil
        transcribingStatusText = nil
        confirmationText = nil
        errorMessage = nil
        let front = frontmostAppProvider()
        if front?.bundleIdentifier != Bundle.main.bundleIdentifier {
            frontmostAppOnRecordStart = front
            recordStartInsertionHandler = dictationInsertionHandlerProvider()
        } else {
            frontmostAppOnRecordStart = nil
            recordStartInsertionHandler = nil
        }
        logDiagnostic("record_start", details: [
            "pressToTalk": boolString(pressToTalk),
            "capturedTargetApp": frontmostAppOnRecordStart?.bundleIdentifier ?? "nil",
            "hasCapturedInsertion": boolString(recordStartInsertionHandler != nil),
            "recordCommandUptimeMs": String(commandUptimeMs),
        ])
        barInitiatedRecording = true
        if pressToTalk, isConnected {
            mode = .recording
            onModeChange?(.recording)
            expandFromCollapse()
        }

        // Safety timeout: keep bar-initiated dictation state from leaking if the
        // daemon disappears, without ending normal long-form dictation.
        barInitiatedTimeout?.cancel()
        recordingIdleCleanupTask?.cancel()
        barInitiatedTimeout = Task { @MainActor in
            try? await Task.sleep(for: barInitiatedSafetyTimeout)
            if !Task.isCancelled, barInitiatedRecording {
                guard mode != .transcribing else { return }
                barInitiatedRecording = false
                frontmostAppOnRecordStart = nil
                recordStartInsertionHandler = nil
            }
        }

        sendIntent(command: .record, payload: [
            "cmd": "record",
            "silence_mode": "thoughtful",
            "timeout_seconds": 3600,
            "press_to_talk": pressToTalk,
        ])
    }

    // MARK: - State updates from socket events

    public func acknowledgePolishMenuSignal() {
        guard polishMenuSignalPending else { return }
        polishMenuSignalPending = false
        onPolishStatusChange?()
    }

    public func dismissPolishDegradation() {
        guard let degradation = polishDegradation else { return }
        dismissedPolishDegradation = degradation
        polishDegradation = nil
        polishMenuSignalPending = false
        onPolishStatusChange?()
    }

    public func handleEvent(_ event: [String: Any]) {
        guard let type = event["type"] as? String else { return }

        switch type {
        case "state":
            guard let stateStr = event["state"] as? String else { return }
            switch stateStr {
            case "idle":
                let idleSource = event["source"] as? String
                if barInitiatedRecording, mode == .transcribing {
                    if idleSource == "recording", deferredFinalTranscriptionTask != nil {
                        pendingRecordingIdleAfterFinal = true
                        return
                    }

                    // Ignore stale idle from losing clients so the bar keeps
                    // the thinking state until the winning transcription lands.
                    // If a final transcript is already pending its minimum UI
                    // display window, ignore even recording-sourced idle so the
                    // pill stays blue until paste/history handling completes.
                    if idleSource != "recording" {
                        return
                    }
                }
                // AIDEV-NOTE: Do not reset barInitiatedRecording on generic idle.
                // Non-recording idle can still arrive from passive clients or
                // playback while the command-owning daemon is transcribing. These
                // stale idle events would kill the paste flag. Recording-sourced
                // idle gets a short final-transcript grace before clearing it.
                if idleSource == "recording" {
                    barInitiatedTimeout?.cancel()
                    if historyRetranscriptionRequest.currentPath() != nil,
                       deferredFinalTranscriptionTask == nil {
                        historyRetranscriptionRequest.clear(removeSuppression: true)
                    }
                    scheduleRecordingIdleCleanupIfNeeded()
                }
                if idleSource == "recording", mode == .error, errorMessage != nil {
                    return
                }
                enterIdleState(clearQueue: idleSource == "playback")
            case "speaking":
                cancelDeferredFinalTranscriptionUnlessHistoryRetranscription()
                pendingRecordingIdleAfterFinal = false
                pendingIdleAfterAutoPasteCompletion = false
                pendingRecoveredTranscriptionPaste = false
                clearHistoryRetranscriptionRequest(removeSuppression: false)
                clearRecordStartLateRecovery(clearPasteTarget: true)
                transcribingStartedAt = nil
                mode = .speaking
                statusText = event["text"] as? String ?? ""
                canReplay = true
                hotkeyPhase = .idle
                onModeChange?(.speaking)
                expandFromCollapse()
            case "recording":
                cancelDeferredFinalTranscriptionUnlessHistoryRetranscription()
                if pendingIntent?.command == .record {
                    recordStartAckTimeoutTask?.cancel()
                    pendingIntent = nil
                } else if canRecoverLateRecordStart {
                    barInitiatedRecording = true
                }
                clearRecordStartLateRecovery(clearPasteTarget: false)
                pendingRecordingIdleAfterFinal = false
                pendingIdleAfterAutoPasteCompletion = false
                pendingRecoveredTranscriptionPaste = false
                clearHistoryRetranscriptionRequest(removeSuppression: false)
                transcribingStartedAt = nil
                transcribingStatusText = nil
                errorMessage = nil
                if recordingStateUptimeMs == nil {
                    recordingStateUptimeMs = currentRecordingUptimeMs()
                    didLogFirstRecordingAudioLevel = false
                }
                mode = .recording
                recordingMode = event["mode"] as? String
                silenceMode = event["silence_mode"] as? String
                speechDetected = false
                localRecordingLevel = nil
                refreshAudioLevel()
                canReplay = false // User recording — replay not applicable
                onModeChange?(.recording)
                expandFromCollapse()
            case "transcribing":
                enterTranscribingMode()
            default:
                break
            }

        case "ack":
            handleAckEvent(event)

        case "transcription_status":
            guard mode == .transcribing else { return }
            let message = (event["message"] as? String)?
                .trimmingCharacters(in: .whitespacesAndNewlines)
            transcribingStatusText = message?.isEmpty == false ? message : nil

        case "polish_degraded":
            guard let reason = event["reason"] as? String,
                  let hint = event["hint"] as? String
            else { return }
            let degradation = STTPolishDegradation(reason: reason, hint: hint)
            guard degradation != polishDegradation,
                  degradation != dismissedPolishDegradation
            else { return }
            polishDegradation = degradation
            polishMenuSignalPending = true
            onPolishStatusChange?()

        case "polish_ready":
            guard polishDegradation != nil || dismissedPolishDegradation != nil || polishMenuSignalPending
            else { return }
            polishDegradation = nil
            dismissedPolishDegradation = nil
            polishMenuSignalPending = false
            onPolishStatusChange?()

        case "speech":
            if let detected = event["detected"] as? Bool {
                speechDetected = detected
            }

        case "transcription":
            if let text = event["text"] as? String {
                let isPartial = (event["partial"] as? Bool) == true
                if !isPartial {
                    lastTranscriptionPolished = event["polished"] as? Bool
                    lastTranscriptionPolishReason = event["polish_reason"] as? String
                }
                let recordingPath = (event["recording_path"] as? String)?
                    .trimmingCharacters(in: .whitespacesAndNewlines)
                let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
                guard !trimmed.isEmpty else {
                    if isPartial {
                        return
                    }
                    failTranscription()
                    return
                }

                if isPartial {
                    transcript = trimmed
                    return
                }

                if scheduleFinalTranscriptionAfterMinimumDisplayIfNeeded(
                    trimmed,
                    recordingPath: recordingPath?.isEmpty == false ? recordingPath : nil
                ) {
                    return
                }
                handleFinalTranscription(
                    trimmed,
                    recordingPath: recordingPath?.isEmpty == false ? recordingPath : nil
                )
            }

        case "subtitle":
            if let words = event["words"] as? [[String: Any]] {
                wordBoundaries = words.compactMap { w in
                    // JSONSerialization may decode numbers as Int or Double
                    guard let offset = (w["offset_ms"] as? Int) ?? (w["offset_ms"] as? Double).map({ Int($0) }),
                          let duration = (w["duration_ms"] as? Int) ?? (w["duration_ms"] as? Double).map({ Int($0) }),
                          let text = w["text"] as? String
                    else { return nil }
                    return (offsetMs: offset, durationMs: duration, text: text)
                }
            }

        case "queue":
            if let depth = event["depth"] as? Int {
                queueDepth = max(0, depth)
            }
            if let items = event["items"] as? [[String: Any]] {
                queueItems = items.compactMap { item in
                    guard let text = item["text"] as? String,
                          let voice = item["voice"] as? String,
                          let priority = item["priority"] as? String,
                          let isCurrent = item["is_current"] as? Bool
                    else { return nil }
                    let rawProgress = (item["progress"] as? Double)
                        ?? (item["progress"] as? Int).map(Double.init)
                        ?? 0
                    return QueueItemState(
                        text: text,
                        voice: voice,
                        priority: priority,
                        isCurrent: isCurrent,
                        progress: min(1, max(0, rawProgress))
                    )
                }
            } else if queueDepth == 0 {
                queueItems = []
            }

        case "audio_level":
            if let rms = event["rms"] as? Double {
                socketAudioLevel = Self.clampAudioLevel(rms)
                refreshAudioLevel()
                logFirstRecordingAudioLevelIfNeeded(socketRMS: socketAudioLevel)
            }

        case "command_mode":
            handleCommandModeEvent(event)

        case "vocabulary", "vocab_list", "stt_vocabulary":
            applyVocabularyEvent(event)

        case "clip_marker":
            if let id = event["marker_id"] as? String,
               let label = event["label"] as? String,
               let source = event["source"] as? String,
               let status = event["status"] as? String {
                activeClipMarker = ClipMarkerState(id: id, label: label, source: source, status: status)
                expandFromCollapse()
            }

        case "error":
            let showDuringBarRecording = event["show_during_bar_recording"] as? Bool ?? false
            let shouldShowError = showDuringBarRecording || !barInitiatedRecording
            if shouldShowError {
                transcriptionTimeoutTask?.cancel()
                recordStartAckTimeoutTask?.cancel()
                pendingRecoveredTranscriptionPaste = false
                clearHistoryRetranscriptionRequest(removeSuppression: true)
            }
            // AIDEV-NOTE: NEVER reset barInitiatedRecording on error.
            // With multiple MCP clients, failing clients broadcast errors while
            // the successful client is still recording. Show error UI only if
            // we're not in an active bar-initiated recording.
            if showDuringBarRecording {
                barInitiatedRecording = false
                barInitiatedTimeout?.cancel()
                recordingIdleCleanupTask?.cancel()
                cancelDeferredFinalTranscription()
                pendingRecordingIdleAfterFinal = false
                pendingIdleAfterAutoPasteCompletion = false
                clearRecordStartLateRecovery(clearPasteTarget: false)
                transcribingStartedAt = nil
                transcribingStatusText = nil
                frontmostAppOnRecordStart = nil
                recordStartInsertionHandler = nil
            }
            if shouldShowError {
                mode = .error
                errorMessage = event["message"] as? String ?? "Unknown error"
                expandFromCollapse()
            }

        default:
            break
        }
    }

    private func applyVocabularyEvent(_ event: [String: Any]) {
        var appliedSnapshot = false

        if let entries = event["entries"] as? [[String: Any]] {
            let preview = STTVocabularyPreview(
                updatedAt: event["updated_at"] as? String,
                entries: entries.compactMap { entry in
                    guard let canonical = entry["canonical"] as? String else { return nil }
                    return STTDictionaryEntry(
                        canonical: canonical,
                        variants: entry["variants"] as? [String] ?? []
                    )
                }
            )
            transcriptionVocabularyTerms = Self.normalizeVocabularyTerms(preview.promptTerms)
            transcriptionVocabularyAliases = Self.normalizeVocabularyAliases(preview.aliases)
            appliedSnapshot = true
        }

        if let promptTerms = event["prompt_terms"] as? [String] {
            transcriptionVocabularyTerms = Self.normalizeVocabularyTerms(promptTerms)
            appliedSnapshot = true
        }

        if let aliases = event["aliases"] as? [[String: Any]] {
            transcriptionVocabularyAliases = Self.normalizeVocabularyAliases(
                aliases.compactMap { alias in
                    guard let from = alias["from"] as? String,
                          let to = alias["to"] as? String
                    else { return nil }
                    return STTVocabularyAliasPreview(from: from, to: to)
                }
            )
            appliedSnapshot = true
        }

        if !appliedSnapshot {
            refreshTranscriptionVocabulary()
        }
    }

    public func setConnectionStatus(_ connected: Bool) {
        let previous = isConnected
        isConnected = connected
        guard previous != connected else { return }

        onConnectionChange?(connected)

        if connected {
            if mode == .disconnected {
                mode = .idle
                onModeChange?(.idle)
                startCollapseTimer()
            }
            return
        }

        transcriptionTimeoutTask?.cancel()
        barInitiatedTimeout?.cancel()
        recordingIdleCleanupTask?.cancel()
        cancelDeferredFinalTranscription()
        recordStartAckTimeoutTask?.cancel()
        clearRecordStartLateRecovery(clearPasteTarget: false)
        pendingRecordingIdleAfterFinal = false
        pendingIdleAfterAutoPasteCompletion = false
        pendingRecoveredTranscriptionPaste = false
        clearHistoryRetranscriptionRequest(removeSuppression: true)
        keepsPasteFlowEnvelope = false
        transcribingStartedAt = nil
        transcribingStatusText = nil
        barInitiatedRecording = false
        pendingIntent = nil
        frontmostAppOnRecordStart = nil
        recordStartInsertionHandler = nil
        speechDetected = false
        recordingMode = nil
        silenceMode = nil
        errorMessage = nil
        hotkeyPhase = .idle
        resetAudioLevels()
        mode = .disconnected
        onModeChange?(.disconnected)
        collapseTimer?.cancel()
        isCollapsed = false
    }

    // MARK: - Idle collapse

    private func startCollapseTimer() {
        guard modalInteractionDepth == 0 else { return }
        collapseTimer?.cancel()
        collapseTimer = Task { @MainActor in
            try? await Task.sleep(for: .seconds(idleCollapseDelay))
            if !Task.isCancelled, mode == .idle, !isHovering, modalInteractionDepth == 0 {
                withAnimation(.smooth(duration: 0.3)) {
                    isCollapsed = true
                }
            }
        }
    }

    private func expandFromCollapse() {
        collapseTimer?.cancel()
        withAnimation(.smooth(duration: 0.3)) {
            isCollapsed = false
        }
    }

    /// Called when hover state changes.
    public func setHovering(_ hovering: Bool) {
        isHovering = hovering
        if hovering, isCollapsed {
            withAnimation(.smooth(duration: 0.3)) {
                isCollapsed = false
            }
        }
        if !hovering, mode == .idle {
            startCollapseTimer()
        }
    }

    public func beginModalInteraction() {
        modalInteractionDepth += 1
        collapseTimer?.cancel()
        expandFromCollapse()
    }

    public func endModalInteraction() {
        modalInteractionDepth = max(0, modalInteractionDepth - 1)
        guard modalInteractionDepth == 0 else { return }
        expandFromCollapse()
    }

    public func setHotkeyEnabled(_ enabled: Bool) {
        hotkeyEnabled = enabled
        if !enabled {
            hotkeyPhase = .idle
        }
    }

    public func setHotkeyPhase(_ phase: HotkeyPhase) {
        hotkeyPhase = hotkeyEnabled ? phase : .idle
        if hotkeyPhase != .idle {
            expandFromCollapse()
        }
    }

    private func rememberRecentTranscription(_ text: String, recordingPath: String? = nil) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        let trimmedPath = recordingPath?.trimmingCharacters(in: .whitespacesAndNewlines)
        let normalizedPath = trimmedPath?.isEmpty == false ? trimmedPath : nil
        let entry = RecentTranscriptionEntry(text: trimmed, recordingPath: normalizedPath)
        if let normalizedPath,
           let existingIndex = recentTranscriptionEntries.firstIndex(where: { $0.recordingPath == normalizedPath }) {
            recentTranscriptionEntries[existingIndex] = entry
        } else {
            recentTranscriptionEntries.removeAll { existing in
                existing.text == trimmed || (normalizedPath != nil && existing.recordingPath == normalizedPath)
            }
            recentTranscriptionEntries.insert(entry, at: 0)
        }
        if recentTranscriptionEntries.count > Self.maxRecentTranscriptions {
            recentTranscriptionEntries = Array(recentTranscriptionEntries.prefix(Self.maxRecentTranscriptions))
        }
        recentTranscriptions = recentTranscriptionEntries.map(\.text)
        recentTranscriptionsSaver(recentTranscriptions)
        recentTranscriptionEntriesSaver(recentTranscriptionEntries)
    }

    private func refreshTranscriptionVocabulary() {
        transcriptionVocabularyTerms = Self.normalizeVocabularyTerms(transcriptionVocabularyLoader())
        transcriptionVocabularyAliases = Self.normalizeVocabularyAliases(
            transcriptionVocabularyAliasLoader()
        )
    }

    private func refreshAudioLevel() {
        if mode == .recording {
            switch (localRecordingLevel, socketAudioLevel) {
            case let (local?, socket?):
                audioLevel = max(local, socket)
            case let (local?, nil):
                audioLevel = local
            case let (nil, socket?):
                audioLevel = socket
            case (nil, nil):
                audioLevel = nil
            }
        } else {
            audioLevel = socketAudioLevel
        }
    }

    private func resetAudioLevels() {
        socketAudioLevel = nil
        localRecordingLevel = nil
        audioLevel = nil
        recordCommandUptimeMs = nil
        recordingStateUptimeMs = nil
        didLogFirstRecordingAudioLevel = false
    }

    private static func clampAudioLevel(_ level: Double) -> Double {
        min(1, max(0, level))
    }

    private static func normalizeRecentTranscriptions(_ items: [String]) -> [String] {
        var unique: [String] = []
        for raw in items {
            let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty, !unique.contains(trimmed) else { continue }
            unique.append(trimmed)
            if unique.count == maxRecentTranscriptions {
                break
            }
        }
        return unique
    }

    private static func normalizeRecentTranscriptionEntries(
        _ entries: [RecentTranscriptionEntry],
        fallbackTexts: [String] = []
    ) -> [RecentTranscriptionEntry] {
        let sourceEntries = entries.isEmpty
            ? normalizeRecentTranscriptions(fallbackTexts).map { RecentTranscriptionEntry(text: $0) }
            : entries
        var unique: [RecentTranscriptionEntry] = []
        var seenKeys = Set<String>()
        for entry in sourceEntries {
            let text = entry.text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { continue }
            let path = entry.recordingPath?.trimmingCharacters(in: .whitespacesAndNewlines)
            let normalizedPath = path?.isEmpty == false ? path : nil
            let key = normalizedPath ?? text
            guard !seenKeys.contains(key) else { continue }
            seenKeys.insert(key)
            unique.append(RecentTranscriptionEntry(text: text, recordingPath: normalizedPath))
            if unique.count == maxRecentTranscriptions {
                break
            }
        }
        return unique
    }

    private static func normalizeVocabularyTerms(_ items: [String]) -> [String] {
        var unique: [String] = []
        for raw in items {
            let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty, !unique.contains(trimmed) else { continue }
            unique.append(trimmed)
            if unique.count == maxVocabularyTerms {
                break
            }
        }
        return unique
    }

    private static func normalizeVocabularyAliases(
        _ items: [STTVocabularyAliasPreview]
    ) -> [STTVocabularyAliasPreview] {
        var unique: [STTVocabularyAliasPreview] = []
        for item in items {
            let from = item.from.trimmingCharacters(in: .whitespacesAndNewlines)
            let to = item.to.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !from.isEmpty, !to.isEmpty else { continue }
            let normalized = STTVocabularyAliasPreview(from: from, to: to)
            guard !unique.contains(normalized) else { continue }
            unique.append(normalized)
            if unique.count == maxVocabularyAliases {
                break
            }
        }
        return unique
    }

    public static func loadRecentTranscriptions() -> [String] {
        UserDefaults.standard.stringArray(forKey: recentTranscriptionsDefaultsKey) ?? []
    }

    public static func saveRecentTranscriptions(_ items: [String]) {
        UserDefaults.standard.set(items, forKey: recentTranscriptionsDefaultsKey)
    }

    public static func loadRecentTranscriptionEntries() -> [RecentTranscriptionEntry] {
        guard let data = UserDefaults.standard.data(forKey: recentTranscriptionEntriesDefaultsKey),
              let decoded = try? JSONDecoder().decode([RecentTranscriptionEntry].self, from: data)
        else {
            return []
        }
        return normalizeRecentTranscriptionEntries(decoded)
    }

    public static func saveRecentTranscriptionEntries(_ items: [RecentTranscriptionEntry]) {
        guard let data = try? JSONEncoder().encode(normalizeRecentTranscriptionEntries(items)) else {
            return
        }
        UserDefaults.standard.set(data, forKey: recentTranscriptionEntriesDefaultsKey)
    }

    private func startTranscriptionTimeout() {
        transcriptionTimeoutTask?.cancel()
        let usesExtendedTimeout = barInitiatedRecording || historyRetranscriptionRequest.isPending
        let timeout = usesExtendedTimeout ? barInitiatedTranscriptionTimeout : transcriptionTimeout
        transcriptionTimeoutTask = Task { @MainActor [weak self] in
            try? await Task.sleep(for: timeout)
            guard let self, !Task.isCancelled, mode == .transcribing else { return }
            failTranscription()
        }
    }

    private func enterIdleState(clearQueue: Bool) {
        mode = .idle
        statusText = ""
        speechDetected = false
        recordingMode = nil
        silenceMode = nil
        errorMessage = nil
        transcriptionTimeoutTask?.cancel()
        transcribingStartedAt = nil
        transcribingStatusText = nil
        resetAudioLevels()
        wordBoundaries = []
        if clearQueue {
            queueDepth = 0
            queueItems = []
        }
        hotkeyPhase = .idle
        onModeChange?(.idle)
        startCollapseTimer()
    }

    private func cancelDeferredFinalTranscription() {
        deferredFinalTranscriptionTask?.cancel()
        deferredFinalTranscriptionTask = nil
        deferredFinalTranscriptionRecordingPath = nil
    }

    private func cancelDeferredFinalTranscriptionUnlessHistoryRetranscription() {
        guard let path = deferredFinalTranscriptionRecordingPath,
              historyRetranscriptionRequest.suppressesPaste(for: path)
        else {
            cancelDeferredFinalTranscription()
            return
        }
    }

    private func clearHistoryRetranscriptionRequest(removeSuppression: Bool) {
        historyRetranscriptionRequest.clear(removeSuppression: removeSuppression)
    }

    private func enterTranscribingMode() {
        let modeChanged = mode != .transcribing
        mode = .transcribing
        if modeChanged || transcribingStartedAt == nil {
            transcribingStartedAt = currentDateProvider()
        }
        if modeChanged {
            transcribingStatusText = nil
        }
        statusText = ""
        localRecordingLevel = nil
        refreshAudioLevel()
        startTranscriptionTimeout()
        hotkeyPhase = .idle
        logDiagnostic("state_transcribing", details: [
            "barInitiatedRecording": boolString(barInitiatedRecording),
            "capturedTargetApp": frontmostAppOnRecordStart?.bundleIdentifier ?? "nil",
            "hasCapturedInsertion": boolString(recordStartInsertionHandler != nil),
            "source": modeChanged ? "transition" : "refresh",
        ])
        if modeChanged {
            onModeChange?(.transcribing)
        }
        expandFromCollapse()
    }

    private func scheduleFinalTranscriptionAfterMinimumDisplayIfNeeded(
        _ text: String,
        recordingPath: String?
    ) -> Bool {
        guard mode == .transcribing, let transcribingStartedAt else { return false }

        let elapsed = currentDateProvider().timeIntervalSince(transcribingStartedAt)
        let remainingDisplayDuration = minimumTranscribingDisplayDuration - elapsed
        guard remainingDisplayDuration > 0 else { return false }

        cancelDeferredFinalTranscription()
        deferredFinalTranscriptionRecordingPath = recordingPath
        deferredFinalTranscriptionTask = Task { @MainActor [weak self] in
            try? await Task.sleep(for: .seconds(remainingDisplayDuration))
            guard let self, !Task.isCancelled else { return }
            deferredFinalTranscriptionTask = nil
            deferredFinalTranscriptionRecordingPath = nil
            handleFinalTranscription(text, recordingPath: recordingPath)
        }
        return true
    }

    private func handleFinalTranscription(_ text: String, recordingPath: String? = nil) {
        transcriptionTimeoutTask?.cancel()
        cancelDeferredFinalTranscription()
        transcribingStartedAt = nil
        transcribingStatusText = nil
        clearRecordStartLateRecovery(clearPasteTarget: false)
        transcript = text
        rememberRecentTranscription(text, recordingPath: recordingPath)
        if recordingPath?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == false {
            onHistoryArchiveChange?()
        }
        refreshTranscriptionVocabulary()
        logDiagnostic("transcription_final", details: [
            "textLength": String(text.count),
            "barInitiatedRecording": boolString(barInitiatedRecording),
            "capturedTargetApp": frontmostAppOnRecordStart?.bundleIdentifier ?? "nil",
            "hasCapturedInsertion": boolString(recordStartInsertionHandler != nil),
            "recordingPath": recordingPath ?? "nil",
        ])

        let wasHistoryRetranscription = recordingPath.map { path in
            historyRetranscriptionRequest.suppressesPaste(for: path)
        } ?? false
        let shouldAutoPaste = barInitiatedRecording && !wasHistoryRetranscription
        let shouldPasteRecoveredTranscription = pendingRecoveredTranscriptionPaste && !wasHistoryRetranscription
        let shouldApplyPendingRecordingIdle = pendingRecordingIdleAfterFinal
        pendingRecordingIdleAfterFinal = false
        pendingRecoveredTranscriptionPaste = false
        if wasHistoryRetranscription, let recordingPath {
            historyRetranscriptionRequest.finish(path: recordingPath)
        }
        pendingIdleAfterAutoPasteCompletion =
            (shouldAutoPaste || shouldPasteRecoveredTranscription) && mode == .transcribing

        if shouldAutoPaste {
            barInitiatedRecording = false
            barInitiatedTimeout?.cancel()
            recordingIdleCleanupTask?.cancel()
            pasteTranscript(text, for: resolvedPasteTarget(forRepaste: false), plan: .autoPaste)
        } else if shouldPasteRecoveredTranscription {
            pasteTranscript(text, for: resolvedPasteTarget(forRepaste: true), plan: .repaste)
        }

        if shouldApplyPendingRecordingIdle, !shouldAutoPaste, !shouldPasteRecoveredTranscription {
            enterIdleState(clearQueue: false)
        }
    }

    private func scheduleRecordingIdleCleanupIfNeeded() {
        guard barInitiatedRecording else { return }

        recordingIdleCleanupTask?.cancel()
        let grace = recordingIdleFinalTranscriptGrace
        recordingIdleCleanupTask = Task { @MainActor [weak self] in
            try? await Task.sleep(for: grace)
            guard let self, !Task.isCancelled, barInitiatedRecording, mode != .transcribing else { return }
            barInitiatedRecording = false
            frontmostAppOnRecordStart = nil
            recordStartInsertionHandler = nil
        }
    }

    private func failTranscription() {
        transcriptionTimeoutTask?.cancel()
        barInitiatedTimeout?.cancel()
        recordingIdleCleanupTask?.cancel()
        cancelDeferredFinalTranscription()
        recordStartAckTimeoutTask?.cancel()
        pendingRecordingIdleAfterFinal = false
        pendingIdleAfterAutoPasteCompletion = false
        pendingRecoveredTranscriptionPaste = false
        clearHistoryRetranscriptionRequest(removeSuppression: true)
        clearRecordStartLateRecovery(clearPasteTarget: false)
        keepsPasteFlowEnvelope = false
        transcribingStartedAt = nil
        transcribingStatusText = nil
        barInitiatedRecording = false
        pendingIntent = nil
        frontmostAppOnRecordStart = nil
        recordStartInsertionHandler = nil
        speechDetected = false
        recordingMode = nil
        silenceMode = nil
        resetAudioLevels()
        mode = .error
        errorMessage = "Transcription failed"
        onModeChange?(.error)
        expandFromCollapse()
    }

    // MARK: - Paste transcription at cursor

    private func resolvedPasteTarget(
        forRepaste repaste: Bool,
        useSettingsHistoryTarget: Bool = false
    ) -> NSRunningApplication? {
        let currentFront = frontmostAppProvider()
        let isSelf = currentFront?.bundleIdentifier == Bundle.main.bundleIdentifier

        if useSettingsHistoryTarget {
            return settingsHistoryPasteTargetApp ?? (!isSelf ? currentFront : nil) ?? lastPasteTargetApp
        }

        if repaste {
            return (!isSelf ? currentFront : nil) ?? lastPasteTargetApp
        }

        return (!isSelf ? currentFront : nil) ?? frontmostAppOnRecordStart
    }

    /// Refocuses the target app and pastes text via Cmd+V.
    private func pasteTranscript(
        _ text: String,
        for targetApp: NSRunningApplication?,
        plan: VoicePastePlan,
        allowAXInsertion: Bool = false
    ) {
        let recordStartTargetApp = frontmostAppOnRecordStart
        let insertionHandler = plan == .autoPaste ? recordStartInsertionHandler : nil
        let targetBundleID = targetApp?.bundleIdentifier ?? "nil"
        logDiagnostic("paste_begin", details: [
            "plan": String(describing: plan),
            "targetApp": targetBundleID,
            "textLength": String(text.count),
            "hasCapturedInsertion": boolString(insertionHandler != nil),
            "axTrusted": boolString(accessibilityTrustChecker(false)),
        ])

        if let pasteHandler {
            if let targetApp {
                lastPasteTargetApp = targetApp
            }
            frontmostAppOnRecordStart = nil
            recordStartInsertionHandler = nil
            finishPasteConfirmation(
                outcome: pasteHandler(text) ? .pasted : .failed(Self.genericPasteFailureMessage),
                text: text
            )
            return
        } else {
            guard let targetApp else {
                frontmostAppOnRecordStart = nil
                recordStartInsertionHandler = nil
                logDiagnostic("paste_no_target", details: [
                    "plan": String(describing: plan),
                    "hasCapturedInsertion": boolString(insertionHandler != nil),
                ])
                finishPasteConfirmation(outcome: .failed(Self.genericPasteFailureMessage), text: text)
                return
            }

            let pasteDelay = plan == .autoPaste ? pasteConfirmationDelay : plan.pasteDelay
            pasteScheduler(plan.activationDelay) { [weak self] in
                guard let self else { return }
                let currentFront = frontmostAppProvider()
                let currentIsSelf = currentFront?.bundleIdentifier == Bundle.main.bundleIdentifier
                let currentPasteTarget = !currentIsSelf ? currentFront : nil
                let pasteTarget: NSRunningApplication? = if plan == .autoPaste {
                    currentPasteTarget ?? targetApp
                } else {
                    targetApp
                }
                let pasteTargetBundleID = pasteTarget?.bundleIdentifier ?? "nil"
                let targetMatchesRecordStart = Self.sameApp(pasteTarget, recordStartTargetApp)
                let targetMatchesSettingsHistory = Self.sameApp(pasteTarget, settingsHistoryPasteTargetApp)
                let capturedInsertionHandler =
                    plan == .autoPaste && targetMatchesRecordStart && currentPasteTarget == nil
                        ? insertionHandler
                        : allowAXInsertion && targetMatchesSettingsHistory
                        ? settingsHistoryInsertionHandler
                        : nil

                guard let pasteTarget else {
                    logDiagnostic("paste_no_target", details: [
                        "plan": String(describing: plan),
                        "hasCapturedInsertion": boolString(capturedInsertionHandler != nil),
                    ])
                    finishPasteConfirmation(outcome: .failed(Self.genericPasteFailureMessage), text: text)
                    return
                }

                logDiagnostic("paste_before_activate", details: [
                    "plan": String(describing: plan),
                    "targetApp": pasteTargetBundleID,
                    "hasCapturedInsertion": boolString(capturedInsertionHandler != nil),
                ])
                targetAppActivator(pasteTarget)
                lastPasteTargetApp = pasteTarget
                logDiagnostic("paste_after_activate", details: [
                    "plan": String(describing: plan),
                    "targetApp": pasteTargetBundleID,
                    "hasCapturedInsertion": boolString(capturedInsertionHandler != nil),
                ])

                pasteScheduler(pasteDelay) { [weak self] in
                    guard let self else { return }
                    if plan == .autoPaste, insertionHandler != nil, !targetMatchesRecordStart {
                        logDiagnostic("paste_ax_insert_skipped", details: [
                            "plan": String(describing: plan),
                            "targetApp": pasteTargetBundleID,
                            "reason": "target_mismatch",
                        ])
                    }

                    let freshInsertionHandler =
                        plan == .autoPaste || (allowAXInsertion && capturedInsertionHandler == nil)
                            ? dictationInsertionHandlerProvider()
                            : nil
                    if let freshInsertionHandler, freshInsertionHandler(text) {
                        logDiagnostic("paste_ax_insert_success", details: [
                            "plan": String(describing: plan),
                            "targetApp": pasteTargetBundleID,
                            "source": "fresh",
                        ])
                        finishPasteConfirmation(outcome: .insertedAtCursor, text: text)
                        return
                    }

                    if let capturedInsertionHandler,
                       capturedInsertionHandler(text) {
                        logDiagnostic("paste_ax_insert_success", details: [
                            "plan": String(describing: plan),
                            "targetApp": pasteTargetBundleID,
                            "source": "captured",
                        ])
                        finishPasteConfirmation(outcome: .insertedAtCursor, text: text)
                        return
                    }

                    logDiagnostic("paste_ax_insert_miss", details: [
                        "plan": String(describing: plan),
                        "targetApp": pasteTargetBundleID,
                        "hadCapturedInsertion": boolString(capturedInsertionHandler != nil),
                        "attemptedFreshInsertion": boolString(freshInsertionHandler != nil),
                        "axTrusted": boolString(accessibilityTrustChecker(false)),
                    ])
                    let pasteboardSnapshot = pasteboardSnapshotter()
                    let changeCountBeforeWrite = pasteboardChangeCountProvider()
                    pasteboardWriter(text)
                    let changeCountAfterWrite = pasteboardChangeCountProvider()
                    let pasteboardTextAfterWrite = pasteboardStringProvider()
                    let clipboardVerified = pasteboardTextAfterWrite == text
                    logDiagnostic("paste_clipboard_write_result", details: [
                        "plan": String(describing: plan),
                        "targetApp": pasteTargetBundleID,
                        "verified": boolString(clipboardVerified),
                        "changeCountBefore": String(changeCountBeforeWrite),
                        "changeCountAfter": String(changeCountAfterWrite),
                        "pasteboardTextLength": String(pasteboardTextAfterWrite?.count ?? 0),
                        "expectedTextLength": String(text.count),
                    ])
                    guard clipboardVerified else {
                        logDiagnostic("paste_clipboard_write_failed", details: [
                            "plan": String(describing: plan),
                            "targetApp": pasteTargetBundleID,
                            "changeCountBefore": String(changeCountBeforeWrite),
                            "changeCountAfter": String(changeCountAfterWrite),
                            "pasteboardTextLength": String(pasteboardTextAfterWrite?.count ?? 0),
                            "expectedTextLength": String(text.count),
                        ])
                        finishPasteConfirmation(outcome: .failed(Self.genericPasteFailureMessage), text: text)
                        return
                    }
                    let pasted = simulatedPasteHandler()
                    scheduleClipboardRestoreIfNeeded(
                        from: pasteboardSnapshot,
                        expectedChangeCount: changeCountAfterWrite
                    )
                    logDiagnostic("paste_cmdv_result", details: [
                        "plan": String(describing: plan),
                        "targetApp": pasteTargetBundleID,
                        "pasted": boolString(pasted),
                    ])
                    finishPasteConfirmation(
                        outcome: Self.pasteOutcome(
                            pasted: pasted,
                            plan: plan
                        ),
                        text: text
                    )
                }
            }
            frontmostAppOnRecordStart = nil
            recordStartInsertionHandler = nil
            return
        }
    }

    private static let genericPasteFailureMessage = "Paste failed — click back into the input and retry"
    private static let pasteFailureRetryMessage = "Paste failed — click input and press Shift+F5"

    private static func pasteOutcome(
        pasted: Bool,
        plan: VoicePastePlan
    ) -> VoicePasteOutcome {
        guard pasted else { return .failed(genericPasteFailureMessage) }
        return .pasted
    }

    private static func sameApp(_ lhs: NSRunningApplication?, _ rhs: NSRunningApplication?) -> Bool {
        guard let lhs, let rhs else { return false }
        if let lhsBundleIdentifier = lhs.bundleIdentifier,
           let rhsBundleIdentifier = rhs.bundleIdentifier {
            return lhsBundleIdentifier == rhsBundleIdentifier
        }

        return lhs.processIdentifier == rhs.processIdentifier
    }

    private func scheduleClipboardRestoreIfNeeded(
        from snapshot: PasteboardSnapshot?,
        expectedChangeCount: Int
    ) {
        guard snapshot != nil else { return }
        pasteScheduler(pasteboardRestoreDelay) { [weak self] in
            self?.restoreClipboardIfNeeded(
                from: snapshot,
                expectedChangeCount: expectedChangeCount
            )
        }
    }

    private func restoreClipboardIfNeeded(
        from snapshot: PasteboardSnapshot?,
        expectedChangeCount: Int
    ) {
        guard let snapshot else { return }

        let currentChangeCount = pasteboardChangeCountProvider()
        guard currentChangeCount == expectedChangeCount else {
            logDiagnostic("paste_clipboard_restore_skipped", details: [
                "expectedChangeCount": String(expectedChangeCount),
                "currentChangeCount": String(currentChangeCount),
            ])
            return
        }

        pasteboardSnapshotRestorer(snapshot)
        logDiagnostic("paste_clipboard_restored", details: [
            "restoredItems": String(snapshot.items.count),
        ])
    }

    private func finishPasteConfirmation(outcome: VoicePasteOutcome, text: String) {
        logDiagnostic("paste_confirmation", details: [
            "outcome": String(describing: outcome),
        ])
        switch outcome {
        case .insertedAtCursor:
            showConfirmation(text, duration: 5.0)
        case .pasted:
            showConfirmation(text, duration: 5.0)
        case let .failed(message):
            showConfirmation(Self.failureMessageWithRetryHint(message), duration: 4.0)
        }

        if pendingIdleAfterAutoPasteCompletion {
            pendingIdleAfterAutoPasteCompletion = false
            pendingRecoveredTranscriptionPaste = false
            historyRetranscriptionRequest.clear(removeSuppression: false)
            enterIdleState(clearQueue: false)
        }
    }

    private func showConfirmation(_ message: String, duration: TimeInterval = 1.5) {
        confirmationText = message
        DispatchQueue.main.asyncAfter(deadline: .now() + duration) { [weak self] in
            if self?.confirmationText == message {
                self?.confirmationText = nil
                self?.keepsPasteFlowEnvelope = false
            }
        }
    }

    private static func failureMessageWithRetryHint(_ message: String) -> String {
        if message == genericPasteFailureMessage {
            return pasteFailureRetryMessage
        }
        return message
    }

    private func sendIntent(
        command: IntentCommand,
        payload: [String: Any],
        trackPending: Bool = true
    ) {
        let id = UUID().uuidString
        var payloadWithID = payload
        payloadWithID["id"] = id
        if trackPending {
            // An early PTT release must not mask a failed record start.
            if command == .stop, pendingIntent?.command == .record {
                sendCommand?(payloadWithID)
                return
            }
            recordStartAckTimeoutTask?.cancel()
            pendingIntent = PendingIntent(id: id, command: command)
            if command == .record {
                scheduleRecordStartAckTimeout(id: id)
            }
        }
        sendCommand?(payloadWithID)
    }

    public func handleCommandDeliveryFailure(
        _ command: [String: Any],
        reason: String = "VoiceLayer is starting"
    ) {
        guard let commandName = command["cmd"] as? String,
              let intentCommand = IntentCommand(rawValue: commandName),
              let id = command["id"] as? String,
              !id.isEmpty
        else {
            return
        }

        handleEvent([
            "type": "ack",
            "command": intentCommand.rawValue,
            "outcome": "reject",
            "id": id,
            "reason": reason,
        ])
    }

    private func scheduleRecordStartAckTimeout(id: String) {
        let timeout = recordStartAckTimeout
        recordStartAckTimeoutTask = Task { @MainActor [weak self] in
            try? await Task.sleep(for: timeout)
            guard let self,
                  !Task.isCancelled,
                  pendingIntent?.id == id,
                  pendingIntent?.command == .record
            else {
                return
            }

            handleEvent([
                "type": "ack",
                "command": IntentCommand.record.rawValue,
                "outcome": IntentOutcome.reject.rawValue,
                "id": id,
                "reason": "VoiceLayer is starting",
            ])
        }
    }

    private func scheduleRecordStartLateRecovery() {
        canRecoverLateRecordStart = true
        recordStartLateRecoveryTask?.cancel()
        let window = recordStartLateRecoveryWindow
        recordStartLateRecoveryTask = Task { @MainActor [weak self] in
            try? await Task.sleep(for: window)
            guard let self, !Task.isCancelled, canRecoverLateRecordStart else { return }
            clearRecordStartLateRecovery(clearPasteTarget: true)
        }
    }

    private func clearRecordStartLateRecovery(clearPasteTarget: Bool) {
        canRecoverLateRecordStart = false
        recordStartLateRecoveryTask?.cancel()
        recordStartLateRecoveryTask = nil
        if clearPasteTarget {
            frontmostAppOnRecordStart = nil
            recordStartInsertionHandler = nil
        }
    }

    private func logDiagnostic(_ event: String, details: [String: String] = [:]) {
        diagnosticLogger?(event, details)
        if Self.shouldMirrorDiagnosticToControlLayer(event) {
            controlLayerEventWriter(event, details)
        }
    }

    private func logFirstRecordingAudioLevelIfNeeded(socketRMS: Double?) {
        guard mode == .recording,
              !didLogFirstRecordingAudioLevel,
              let socketRMS
        else { return }
        let firstAudioUptimeMs = currentRecordingUptimeMs()
        didLogFirstRecordingAudioLevel = true
        var details = [
            "firstAudioLevelUptimeMs": String(firstAudioUptimeMs),
            "socketRms": Self.formatAudioLevel(socketRMS),
        ]
        if let recordCommandUptimeMs {
            details["msSinceRecordCommand"] = String(max(0, firstAudioUptimeMs - recordCommandUptimeMs))
        }
        if let recordingStateUptimeMs {
            details["msSinceRecordingState"] = String(max(0, firstAudioUptimeMs - recordingStateUptimeMs))
        }
        logDiagnostic("recording_first_audio_level", details: details)
    }

    private func currentRecordingUptimeMs() -> Int {
        Int((recordingTimingClock() * 1000).rounded())
    }

    private static func formatAudioLevel(_ level: Double) -> String {
        String(format: "%.4f", level)
    }

    private static func shouldMirrorDiagnosticToControlLayer(_ event: String) -> Bool {
        event == "transcription_final" ||
            event == "repaste_requested" ||
            event == "copy_transcript" ||
            event.hasPrefix("paste_")
    }

    private func boolString(_ value: Bool) -> String {
        value ? "true" : "false"
    }

    private func notifyPanelLayoutChangedIfNeeded(_ changed: Bool) {
        guard changed else { return }
        DispatchQueue.main.async { [weak self] in
            self?.onPanelLayoutChange?()
        }
    }

    private func handleAckEvent(_ event: [String: Any]) {
        guard let ack = SocketAckEvent(event: event) else {
            return
        }

        onAckEvent?(ack)

        if ack.command == .retranscribeRecording,
           historyRetranscriptionRequest.matchesIntent(id: ack.id) {
            let path = historyRetranscriptionRequest.currentPath()
            historyRetranscriptionRequest.acknowledgeIntent()
            if ack.outcome != .accept {
                historyRetranscriptionRequest.reject(path: path)
                showConfirmation(ack.reason ?? "Nothing to transcribe")
            }
            return
        }

        guard pendingIntent?.id == ack.id,
              pendingIntent?.command == ack.command
        else {
            return
        }

        recordStartAckTimeoutTask?.cancel()
        pendingIntent = nil

        if ack.command == .retranscribeLast, ack.outcome != .accept {
            pendingRecoveredTranscriptionPaste = false
            showConfirmation(ack.reason ?? "Nothing to transcribe")
            return
        }

        if ack.command == .retranscribeRecording, ack.outcome != .accept {
            clearHistoryRetranscriptionRequest(removeSuppression: true)
            showConfirmation(ack.reason ?? "Nothing to transcribe")
            return
        }

        guard ack.command == .record, ack.outcome == .reject else { return }

        let canRecoverLateRecording = ack.reason == "VoiceLayer is starting"
        barInitiatedRecording = false
        barInitiatedTimeout?.cancel()
        recordingIdleCleanupTask?.cancel()
        recordStartAckTimeoutTask?.cancel()
        keepsPasteFlowEnvelope = false
        if canRecoverLateRecording {
            scheduleRecordStartLateRecovery()
        } else {
            clearRecordStartLateRecovery(clearPasteTarget: true)
        }
        hotkeyPhase = .idle
        resetAudioLevels()
        mode = .error
        errorMessage = ack.reason ?? "Unable to start recording"
        onModeChange?(.error)
        expandFromCollapse()
    }

    private func handleCommandModeEvent(_ event: [String: Any]) {
        guard let phaseString = event["phase"] as? String,
              let phase = CommandModePhase(rawValue: phaseString),
              let operation = event["operation"] as? String else {
            return
        }

        commandModeState = CommandModeState(
            phase: phase,
            operation: operation,
            prompt: event["prompt"] as? String
        )
        expandFromCollapse()

        guard phase == .applying, let replacementText = event["replacement_text"] as? String else {
            return
        }

        guard let commandModeApplyHandler else { return }
        let result = commandModeApplyHandler(replacementText)

        switch result {
        case let .axVerified(message):
            commandModeState = CommandModeState(phase: .done, operation: operation, prompt: event["prompt"] as? String)
            showConfirmation(message)
        case let .clipboardFallback(message):
            commandModeState = CommandModeState(
                phase: .fallback,
                operation: operation,
                prompt: event["prompt"] as? String
            )
            showConfirmation(message)
        case let .failed(message):
            commandModeState = CommandModeState(phase: .error, operation: operation, prompt: event["prompt"] as? String)
            mode = .error
            errorMessage = message
        }
    }

    private static func capturePasteboardSnapshot() -> PasteboardSnapshot? {
        let pasteboard = NSPasteboard.general
        let items = pasteboard.pasteboardItems?.compactMap { item -> [String: Data]? in
            let values = item.types.reduce(into: [String: Data]()) { result, type in
                guard !type.rawValue.hasPrefix("dyn."),
                      !type.rawValue.hasPrefix("org.nspasteboard.")
                else {
                    return
                }
                if let data = item.data(forType: type) {
                    result[type.rawValue] = data
                }
            }
            return values.isEmpty ? nil : values
        } ?? []

        guard !items.isEmpty else { return nil }
        return PasteboardSnapshot(changeCount: pasteboard.changeCount, items: items)
    }

    private static func restorePasteboardSnapshot(_ snapshot: PasteboardSnapshot) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        let items = snapshot.items.map { itemSnapshot -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in itemSnapshot {
                item.setData(data, forType: NSPasteboard.PasteboardType(type))
            }
            return item
        }
        pasteboard.writeObjects(items)
        pasteboard.setData(Data(), forType: .voiceBarTransient)
        pasteboard.setData(Data(), forType: .voiceBarAutoGenerated)
    }
}
