import AppKit
@testable import VoiceBarUI
import XCTest

final class VoiceStatePasteTests: XCTestCase {
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    final class FakeRunningApplication: NSRunningApplication, @unchecked Sendable {
        private let fakeBundleIdentifier: String?
        private let fakeProcessIdentifier: pid_t

        init(bundleIdentifier: String?, processIdentifier: pid_t) {
            fakeBundleIdentifier = bundleIdentifier
            fakeProcessIdentifier = processIdentifier
            super.init()
        }

        override var bundleIdentifier: String? {
            fakeBundleIdentifier
        }

        override var processIdentifier: pid_t {
            fakeProcessIdentifier
        }
    }

    func testLoadsPersistedRecentTranscriptionsOnInit() {
        let state = VoiceState(
            recentTranscriptionsLoader: {
                [
                    "persisted latest",
                    "persisted older",
                ]
            },
            transcriptionVocabularyLoader: {
                ["VoiceLayer", "Wispr Flow"]
            },
            transcriptionVocabularyAliasLoader: {
                [STTVocabularyAliasPreview(from: "work claude", to: "orcClaude")]
            }
        )

        XCTAssertEqual(state.recentTranscriptions, [
            "persisted latest",
            "persisted older",
        ])
        XCTAssertEqual(state.transcriptionVocabularyTerms, ["VoiceLayer", "Wispr Flow"])
        XCTAssertEqual(state.transcriptionVocabularyAliases, [
            STTVocabularyAliasPreview(from: "work claude", to: "orcClaude"),
        ])
    }

    func testFinalTranscriptionPersistsRecentTranscriptions() {
        var savedSnapshots: [[String]] = []
        let state = VoiceState(
            recentTranscriptionsLoader: { [] },
            recentTranscriptionsSaver: { savedSnapshots.append($0) }
        )

        state.handleEvent([
            "type": "transcription",
            "text": "persist this transcript",
        ])

        XCTAssertEqual(savedSnapshots.last, ["persist this transcript"])
    }

    func testFinalTranscriptionHistoryAccessoryRequestsPanelLayoutRefresh() {
        let state = VoiceState(
            recentTranscriptionsLoader: { [] },
            recentTranscriptionsSaver: { _ in },
            transcriptionVocabularyLoader: { [] },
            transcriptionVocabularyAliasLoader: { [] }
        )

        assertVoiceStateEventTriggersPanelLayoutRefresh(
            [
                "type": "transcription",
                "text": "new idle history item",
            ],
            state: state
        )
    }

    func testFinalTranscriptionVocabularyAccessoryRequestsPanelLayoutRefresh() {
        var vocabularyTerms: [String] = []
        var vocabularyAliases: [STTVocabularyAliasPreview] = []
        let state = VoiceState(
            recentTranscriptionsLoader: { ["already visible history"] },
            recentTranscriptionsSaver: { _ in },
            transcriptionVocabularyLoader: { vocabularyTerms },
            transcriptionVocabularyAliasLoader: { vocabularyAliases }
        )
        vocabularyTerms = ["VoiceLayer"]
        vocabularyAliases = [STTVocabularyAliasPreview(from: "work claude", to: "orcClaude")]

        assertVoiceStateEventTriggersPanelLayoutRefresh(
            [
                "type": "transcription",
                "text": "refresh vocabulary",
            ],
            state: state
        )
    }

    func testRecordLeavesModeIdleUntilDaemonStateArrives() {
        let state = VoiceState()
        var sentCommand: [String: Any]?
        var modeObservedInsideSend: VoiceMode?
        var callbackModes: [VoiceMode] = []

        state.sendCommand = { command in
            sentCommand = command
            modeObservedInsideSend = state.mode
        }
        state.onModeChange = { mode in
            callbackModes.append(mode)
        }

        state.record()

        XCTAssertEqual(state.mode, .idle)
        XCTAssertEqual(sentCommand?["cmd"] as? String, "record")
        XCTAssertNotNil(sentCommand?["id"] as? String)
        XCTAssertEqual(modeObservedInsideSend, .idle)
        XCTAssertTrue(callbackModes.isEmpty)
    }

    func testSnoozeMovesVoiceStateToDisconnected() {
        let state = VoiceState()

        state.snooze()

        XCTAssertEqual(state.mode, .disconnected)
    }

    func testUnsnoozeReturnsVoiceStateToIdle() {
        let state = VoiceState()
        state.snooze()

        state.unsnooze()

        XCTAssertEqual(state.mode, .idle)
    }

    func testUnsnoozeClearsPasteFlowEnvelopeAndRequestsPanelRelayout() async {
        let state = VoiceState()
        state.snooze()
        XCTAssertTrue(state.keepsPasteFlowEnvelope)
        var relayoutCount = 0
        state.onPanelLayoutChange = {
            relayoutCount += 1
        }

        state.unsnooze()
        try? await Task.sleep(for: .milliseconds(30))

        XCTAssertFalse(state.keepsPasteFlowEnvelope)
        XCTAssertGreaterThanOrEqual(relayoutCount, 1)
    }

    func testModalInteractionSuppressesIdleCollapseAndRestoresExpandedState() async {
        let state = VoiceState()
        state.idleCollapseDelay = 0.01
        state.mode = .idle

        state.beginModalInteraction()
        state.setHovering(false)
        try? await Task.sleep(for: .milliseconds(30))

        XCTAssertFalse(state.isCollapsed)

        state.isCollapsed = true
        state.endModalInteraction()

        XCTAssertFalse(state.isCollapsed)
    }

    func testSnoozeClearsActiveRecordingAudioLevel() throws {
        let state = VoiceState()
        state.handleEvent([
            "type": "state",
            "state": "recording",
            "mode": "vad",
        ])
        state.setLocalRecordingLevel(0.5)
        _ = try XCTUnwrap(state.audioLevel)

        state.snooze()

        XCTAssertEqual(state.mode, .disconnected)
        XCTAssertNil(state.audioLevel)
    }

    func testLocalRecordingLevelOverridesSocketLevelWhileRecording() {
        let state = VoiceState()

        state.handleEvent([
            "type": "state",
            "state": "recording",
            "mode": "vad",
        ])
        state.handleEvent([
            "type": "audio_level",
            "rms": 0.15,
        ])

        state.setLocalRecordingLevel(0.72)

        XCTAssertEqual(try XCTUnwrap(state.audioLevel), 0.72, accuracy: 0.001)
    }

    func testLocalRecordingLevelIgnoredOutsideRecordingMode() {
        let state = VoiceState()
        state.handleEvent([
            "type": "audio_level",
            "rms": 0.24,
        ])

        state.setLocalRecordingLevel(0.72)

        XCTAssertEqual(try XCTUnwrap(state.audioLevel), 0.24, accuracy: 0.001)
    }

    func testStopClearsLocalRecordingLevel() {
        let state = VoiceState()

        state.handleEvent([
            "type": "state",
            "state": "recording",
            "mode": "vad",
        ])
        state.setLocalRecordingLevel(0.72)

        state.cancel()

        XCTAssertNil(state.audioLevel)
    }

    func testCancelDuringRecordingClearsIndicatorToIdleWhenConnected() {
        let state = VoiceState()
        state.setConnectionStatus(true)
        state.handleEvent([
            "type": "state",
            "state": "recording",
            "mode": "vad",
        ])

        state.cancel()

        XCTAssertEqual(state.mode, .idle)
        XCTAssertNil(state.audioLevel)
        XCTAssertFalse(state.speechDetected)
    }

    func testBarInitiatedTranscribingIgnoresStaleIdleUntilTranscriptionArrives() {
        let state = VoiceState()

        state.record()
        state.handleEvent([
            "type": "state",
            "state": "transcribing",
        ])

        state.handleEvent([
            "type": "state",
            "state": "idle",
        ])

        XCTAssertEqual(state.mode, .transcribing)
    }

    func testBarInitiatedTranscribingAcceptsRecordingIdleForSuppressedResult() async {
        let state = VoiceState()
        state.transcriptionTimeout = .milliseconds(20)
        state.recordingIdleFinalTranscriptGrace = .milliseconds(20)

        state.record()
        state.handleEvent([
            "type": "state",
            "state": "transcribing",
        ])

        state.handleEvent([
            "type": "state",
            "state": "idle",
            "source": "recording",
        ])

        try? await Task.sleep(for: .milliseconds(100))

        XCTAssertEqual(state.mode, .idle)
        XCTAssertNil(state.errorMessage)
    }

    func testRecordingIdleWithoutFinalTranscriptionDoesNotAutoPasteNextTranscript() async {
        let state = VoiceState()
        state.sendCommand = { _ in }
        state.recordingIdleFinalTranscriptGrace = .milliseconds(20)

        var pastedTexts: [String] = []
        state.pasteHandler = { text in
            pastedTexts.append(text)
            return true
        }

        state.record()
        state.handleEvent([
            "type": "state",
            "state": "transcribing",
        ])
        state.handleEvent([
            "type": "state",
            "state": "idle",
            "source": "recording",
        ])

        try? await Task.sleep(for: .milliseconds(100))

        state.handleEvent([
            "type": "transcription",
            "text": "unrelated later transcript",
        ])

        XCTAssertEqual(pastedTexts, [])
    }

    func testRecordingIdleCleanupClearsPasteIntentEvenIfModeChanges() async {
        let state = VoiceState()
        state.sendCommand = { _ in }
        state.recordingIdleFinalTranscriptGrace = .milliseconds(20)

        var pastedTexts: [String] = []
        state.pasteHandler = { text in
            pastedTexts.append(text)
            return true
        }

        state.record()
        state.handleEvent([
            "type": "state",
            "state": "transcribing",
        ])
        state.handleEvent([
            "type": "state",
            "state": "idle",
            "source": "recording",
        ])
        state.handleEvent([
            "type": "state",
            "state": "speaking",
            "text": "follow-up prompt",
        ])

        try? await Task.sleep(for: .milliseconds(100))

        state.handleEvent([
            "type": "transcription",
            "text": "unrelated later transcript",
        ])

        XCTAssertEqual(pastedTexts, [])
    }

    func testRecordingIdleBeforeFinalTranscriptionStillAutoPastes() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        state.pasteConfirmationDelay = 0

        var pastedTexts: [String] = []
        state.pasteHandler = { text in
            pastedTexts.append(text)
            return true
        }

        state.record()
        state.handleEvent([
            "type": "state",
            "state": "transcribing",
        ])
        state.handleEvent([
            "type": "state",
            "state": "idle",
            "source": "recording",
        ])
        state.handleEvent([
            "type": "transcription",
            "text": "final text after recording idle",
        ])

        XCTAssertEqual(pastedTexts, ["final text after recording idle"])
    }

    func testLateRecordingStateAfterRecordStartTimeoutStillAutoPastes() async {
        let state = VoiceState()
        state.setConnectionStatus(true)
        state.recordStartAckTimeout = .milliseconds(20)
        state.minimumTranscribingDisplayDuration = 0
        state.sendCommand = { _ in }

        var pastedTexts: [String] = []
        state.pasteHandler = { text in
            pastedTexts.append(text)
            return true
        }

        state.record(pressToTalk: true)
        try? await Task.sleep(for: .milliseconds(100))

        XCTAssertEqual(state.mode, .error)
        XCTAssertNil(state.pendingIntent)

        state.handleEvent([
            "type": "state",
            "state": "recording",
            "mode": "ptt",
        ])
        state.handleEvent([
            "type": "state",
            "state": "transcribing",
        ])
        state.handleEvent([
            "type": "transcription",
            "text": "late successful dictation",
        ])

        XCTAssertEqual(pastedTexts, ["late successful dictation"])
    }

    func testExpiredLateRecordStartRecoveryDoesNotAutoPasteUnrelatedRecording() async {
        let state = VoiceState()
        state.setConnectionStatus(true)
        state.recordStartAckTimeout = .milliseconds(20)
        state.recordStartLateRecoveryWindow = .milliseconds(20)
        state.minimumTranscribingDisplayDuration = 0
        state.sendCommand = { _ in }

        var pastedTexts: [String] = []
        state.pasteHandler = { text in
            pastedTexts.append(text)
            return true
        }

        state.record(pressToTalk: true)
        try? await Task.sleep(for: .milliseconds(100))

        state.handleEvent([
            "type": "state",
            "state": "recording",
            "mode": "ptt",
        ])
        state.handleEvent([
            "type": "state",
            "state": "transcribing",
        ])
        state.handleEvent([
            "type": "transcription",
            "text": "unrelated later dictation",
        ])

        XCTAssertEqual(pastedTexts, [])
    }

    func testFastFinalTranscriptionKeepsBlueStateUntilPendingRecordingIdleCanApply() async {
        let state = VoiceState()
        state.sendCommand = { _ in }
        state.minimumTranscribingDisplayDuration = 0.12
        state.pasteConfirmationDelay = 0

        var pastedTexts: [String] = []
        state.pasteHandler = { text in
            pastedTexts.append(text)
            return true
        }

        state.record()
        state.handleEvent([
            "type": "state",
            "state": "transcribing",
        ])
        state.handleEvent([
            "type": "transcription",
            "text": "fast final transcript",
        ])
        state.handleEvent([
            "type": "state",
            "state": "idle",
            "source": "recording",
        ])

        XCTAssertEqual(state.mode, .transcribing)
        XCTAssertEqual(pastedTexts, [])

        try? await Task.sleep(for: .milliseconds(180))

        XCTAssertEqual(pastedTexts, ["fast final transcript"])
        XCTAssertEqual(state.mode, .idle)
    }

    func testRecordingIdleCleanupDoesNotClearPasteIntentAfterTranscribingResumes() async {
        let state = VoiceState()
        state.sendCommand = { _ in }
        state.recordingIdleFinalTranscriptGrace = .milliseconds(20)
        state.pasteConfirmationDelay = 0
        state.minimumTranscribingDisplayDuration = 0

        var pastedTexts: [String] = []
        state.pasteHandler = { text in
            pastedTexts.append(text)
            return true
        }

        state.record()
        state.handleEvent([
            "type": "state",
            "state": "transcribing",
        ])
        state.handleEvent([
            "type": "state",
            "state": "idle",
            "source": "recording",
        ])
        state.handleEvent([
            "type": "state",
            "state": "transcribing",
        ])

        try? await Task.sleep(for: .milliseconds(100))

        state.handleEvent([
            "type": "transcription",
            "text": "final text after transcribing resumes",
        ])

        XCTAssertEqual(pastedTexts, ["final text after transcribing resumes"])
    }

    func testRepasteUsesStoredTranscript() {
        let state = VoiceState()
        state.pasteConfirmationDelay = 0

        let expectation = expectation(description: "paste invoked")
        var pastedTexts: [String] = []
        state.pasteHandler = { text in
            pastedTexts.append(text)
            expectation.fulfill()
            return true
        }

        state.handleEvent([
            "type": "transcription",
            "text": "test capture from codex",
        ])

        state.repasteLastTranscript()

        wait(for: [expectation], timeout: 1)
        XCTAssertEqual(pastedTexts, ["test capture from codex"])
    }

    func testRepasteLastTranscriptUsesLatestFinalTranscriptInsteadOfCurrentPartial() {
        let state = VoiceState()
        state.pasteConfirmationDelay = 0

        let expectation = expectation(description: "paste invoked")
        var pastedTexts: [String] = []
        state.pasteHandler = { text in
            pastedTexts.append(text)
            expectation.fulfill()
            return true
        }

        state.handleEvent([
            "type": "transcription",
            "text": "stable final transcript",
        ])
        state.handleEvent([
            "type": "transcription",
            "text": "new partial transcript",
            "partial": true,
        ])

        state.repasteLastTranscript()

        wait(for: [expectation], timeout: 1)
        XCTAssertEqual(pastedTexts, ["stable final transcript"])
    }

    func testRepasteTranscriptUsesRequestedHistoryItem() {
        let state = VoiceState()
        state.pasteConfirmationDelay = 0

        let expectation = expectation(description: "paste invoked")
        var pastedTexts: [String] = []
        state.pasteHandler = { text in
            pastedTexts.append(text)
            expectation.fulfill()
            return true
        }

        state.repasteTranscript("older history item")

        wait(for: [expectation], timeout: 1)
        XCTAssertEqual(pastedTexts, ["older history item"])
    }

    func testRepasteTranscriptShowsRequestedHistoryItemInConfirmation() {
        let state = VoiceState()
        state.pasteConfirmationDelay = 0
        state.transcript = "current unrelated transcript"

        let expectation = expectation(description: "paste invoked")
        state.pasteHandler = { _ in
            expectation.fulfill()
            return true
        }

        state.repasteTranscript("older history item")

        wait(for: [expectation], timeout: 1)
        XCTAssertEqual(state.confirmationText, "older history item")
    }

    func testSettingsHistoryRepasteUsesCapturedExternalTargetAndAXInsertion() {
        let state = VoiceState()
        state.pasteScheduler = { _, block in block() }
        let capturedApp = NSRunningApplication.current
        var frontmostApp: NSRunningApplication? = capturedApp
        state.frontmostAppProvider = { frontmostApp }
        var activatedApps: [NSRunningApplication] = []
        state.targetAppActivator = { activatedApps.append($0) }
        var insertionCaptureCount = 0
        var insertedTexts: [String] = []
        var clipboardWrites: [String] = []
        var pasteShortcutPosted = false
        state.dictationInsertionHandlerProvider = {
            insertionCaptureCount += 1
            return { text in
                insertedTexts.append(text)
                return true
            }
        }
        state.pasteboardWriter = { clipboardWrites.append($0) }
        state.simulatedPasteHandler = {
            pasteShortcutPosted = true
            return true
        }

        state.captureSettingsHistoryPasteTarget()
        frontmostApp = NSRunningApplication.current
        state.repasteTranscript("settings history line", source: "settings_history")

        XCTAssertEqual(insertionCaptureCount, 1)
        XCTAssertEqual(activatedApps, [capturedApp])
        XCTAssertEqual(insertedTexts, ["settings history line"])
        XCTAssertEqual(clipboardWrites, [])
        XCTAssertFalse(pasteShortcutPosted)
    }

    func testSettingsHistoryCapturePreservesExternalTargetWhenVoiceBarIsFrontmost() {
        let state = VoiceState()
        state.pasteScheduler = { _, block in block() }
        let externalApp = FakeRunningApplication(
            bundleIdentifier: "com.example.Editor",
            processIdentifier: 4242
        )
        let voiceBarApp = FakeRunningApplication(
            bundleIdentifier: Bundle.main.bundleIdentifier,
            processIdentifier: 5252
        )
        var frontmostApp: NSRunningApplication? = externalApp
        state.frontmostAppProvider = { frontmostApp }
        var activatedApps: [NSRunningApplication] = []
        state.targetAppActivator = { activatedApps.append($0) }
        var insertionCaptureCount = 0
        var insertedTexts: [String] = []
        state.dictationInsertionHandlerProvider = {
            insertionCaptureCount += 1
            return { text in
                insertedTexts.append(text)
                return true
            }
        }
        state.simulatedPasteHandler = {
            XCTFail("settings history paste should use the preserved AX insertion target")
            return false
        }

        state.captureSettingsHistoryPasteTarget()
        frontmostApp = voiceBarApp
        state.captureSettingsHistoryPasteTarget()
        state.repasteTranscript("preserved settings history line", source: "settings_history")

        XCTAssertEqual(insertionCaptureCount, 1)
        XCTAssertEqual(activatedApps, [externalApp])
        XCTAssertEqual(insertedTexts, ["preserved settings history line"])
    }

    func testCopyTranscriptWritesRequestedHistoryItemToPasteboard() {
        let state = VoiceState()

        var copiedTexts: [String] = []
        state.pasteboardWriter = { copiedTexts.append($0) }

        state.copyTranscript("history item to copy")

        XCTAssertEqual(copiedTexts, ["history item to copy"])
        XCTAssertEqual(state.confirmationText, "Copied")
    }

    func testPartialTranscriptionDoesNotAutoPasteOrConsumeFinalPaste() {
        let state = VoiceState()
        var pastedTexts: [String] = []
        state.pasteHandler = { text in
            pastedTexts.append(text)
            return true
        }
        state.sendCommand = { _ in }

        state.record()
        state.handleEvent([
            "type": "transcription",
            "text": "wow",
            "partial": true,
        ])

        XCTAssertEqual(pastedTexts, [])

        state.handleEvent([
            "type": "transcription",
            "text": "this is the full transcript ending with wow",
            "partial": false,
        ])

        XCTAssertEqual(pastedTexts, ["this is the full transcript ending with wow"])
        XCTAssertEqual(state.transcript, "this is the full transcript ending with wow")
    }

    func testAutoPasteUsesRecordedInputInsertionBeforeClipboardFallback() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        var frontmostApp: NSRunningApplication? = NSRunningApplication.current
        state.frontmostAppProvider = { frontmostApp }
        state.pasteScheduler = { _, block in block() }
        state.targetAppActivator = { _ in }

        var insertedTexts: [String] = []
        var pasteShortcutPosted = false
        state.dictationInsertionHandlerProvider = {
            { text in
                insertedTexts.append(text)
                return true
            }
        }
        state.simulatedPasteHandler = {
            pasteShortcutPosted = true
            return true
        }

        state.record()
        frontmostApp = nil
        state.handleEvent([
            "type": "transcription",
            "text": "this is the full transcript ending with wow",
        ])

        XCTAssertEqual(insertedTexts, ["this is the full transcript ending with wow"])
        XCTAssertFalse(pasteShortcutPosted)
        XCTAssertEqual(state.confirmationText, "this is the full transcript ending with wow")
    }

    func testAutoPasteUsesRecordStartInsertionWhenSameTargetIsFrontmostAtPasteTime() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        state.frontmostAppProvider = { NSRunningApplication.current }
        state.pasteScheduler = { _, block in block() }
        state.targetAppActivator = { _ in }

        var insertedTexts: [String] = []
        var clipboardWrites: [String] = []
        var pasteboardString: String?
        var pasteShortcutPosted = false
        state.dictationInsertionHandlerProvider = {
            { text in
                insertedTexts.append(text)
                return true
            }
        }
        state.pasteboardWriter = {
            clipboardWrites.append($0)
            pasteboardString = $0
        }
        state.pasteboardStringProvider = { pasteboardString }
        state.simulatedPasteHandler = {
            pasteShortcutPosted = true
            return true
        }

        state.record()
        state.handleEvent([
            "type": "transcription",
            "text": "paste into the focus that is current on release",
        ])

        XCTAssertEqual(insertedTexts, ["paste into the focus that is current on release"])
        XCTAssertEqual(clipboardWrites, [])
        XCTAssertFalse(pasteShortcutPosted)
        XCTAssertEqual(state.confirmationText, "paste into the focus that is current on release")
    }

    func testAutoPasteUsesFreshFocusedInsertionInsteadOfStaleCapturedInsertionWhenTargetIsFrontmost() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        state.frontmostAppProvider = { NSRunningApplication.current }
        state.pasteScheduler = { _, block in block() }
        state.targetAppActivator = { _ in }

        var captureAttempts = 0
        var staleCapturedTexts: [String] = []
        var freshFocusedTexts: [String] = []
        var clipboardWrites: [String] = []
        var pasteShortcutPosted = false
        state.dictationInsertionHandlerProvider = {
            captureAttempts += 1
            if captureAttempts == 1 {
                return { text in
                    staleCapturedTexts.append(text)
                    return true
                }
            }
            return { text in
                freshFocusedTexts.append(text)
                return true
            }
        }
        state.pasteboardWriter = { clipboardWrites.append($0) }
        state.simulatedPasteHandler = {
            pasteShortcutPosted = true
            return true
        }

        state.record()
        state.handleEvent([
            "type": "transcription",
            "text": "paste into the input focused at release",
        ])

        XCTAssertEqual(captureAttempts, 2)
        XCTAssertEqual(staleCapturedTexts, [])
        XCTAssertEqual(freshFocusedTexts, ["paste into the input focused at release"])
        XCTAssertEqual(clipboardWrites, [])
        XCTAssertFalse(pasteShortcutPosted)
    }

    func testAutoPasteDoesNotUseCapturedInsertionWhenCurrentTargetIsFrontmostAndFreshCaptureIsUnavailable() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        let targetApp = FakeRunningApplication(
            bundleIdentifier: "com.example.TargetApp",
            processIdentifier: 1111
        )
        var frontmostApp: NSRunningApplication? = targetApp
        state.frontmostAppProvider = { frontmostApp }
        state.pasteScheduler = { _, block in block() }
        state.targetAppActivator = { _ in }

        var captureAttempts = 0
        var staleCapturedTexts: [String] = []
        var clipboardWrites: [String] = []
        var pasteboardString: String?
        var pasteShortcutPosted = false
        state.dictationInsertionHandlerProvider = {
            captureAttempts += 1
            guard captureAttempts == 1 else { return nil }
            return { text in
                staleCapturedTexts.append(text)
                return true
            }
        }
        state.pasteboardWriter = {
            clipboardWrites.append($0)
            pasteboardString = $0
        }
        state.pasteboardStringProvider = { pasteboardString }
        state.simulatedPasteHandler = {
            pasteShortcutPosted = true
            return true
        }

        state.record()
        frontmostApp = targetApp
        state.handleEvent([
            "type": "transcription",
            "text": "paste via clipboard instead of stale captured ax",
        ])

        XCTAssertEqual(captureAttempts, 2)
        XCTAssertEqual(staleCapturedTexts, [])
        XCTAssertEqual(clipboardWrites, ["paste via clipboard instead of stale captured ax"])
        XCTAssertTrue(pasteShortcutPosted)
    }

    func testAutoPasteDoesNotUseCapturedInsertionWhenTargetAppRemainsFrontmostAndFreshCaptureIsUnavailable() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        state.frontmostAppProvider = { NSRunningApplication.current }
        state.pasteScheduler = { _, block in block() }
        state.targetAppActivator = { _ in }

        var captureAttempts = 0
        var insertedTexts: [String] = []
        var clipboardWrites: [String] = []
        var pasteboardString: String? = "original clipboard"
        var pasteShortcutPosted = false
        var pasteOutcomes: [String] = []
        state.dictationInsertionHandlerProvider = {
            captureAttempts += 1
            guard captureAttempts == 1 else { return nil }
            return { text in
                insertedTexts.append(text)
                return true
            }
        }
        state.pasteboardWriter = {
            clipboardWrites.append($0)
            pasteboardString = $0
        }
        state.pasteboardStringProvider = { pasteboardString }
        state.simulatedPasteHandler = {
            pasteShortcutPosted = true
            return true
        }
        state.diagnosticLogger = { event, details in
            if event == "paste_confirmation", let outcome = details["outcome"] {
                pasteOutcomes.append(outcome)
            }
        }

        state.record()
        state.handleEvent([
            "type": "transcription",
            "text": "ax should insert without touching clipboard",
        ])

        XCTAssertEqual(captureAttempts, 2)
        XCTAssertEqual(insertedTexts, [])
        XCTAssertEqual(clipboardWrites, ["ax should insert without touching clipboard"])
        XCTAssertEqual(pasteboardString, "ax should insert without touching clipboard")
        XCTAssertTrue(pasteShortcutPosted)
        XCTAssertEqual(pasteOutcomes, ["pasted"])
    }

    func testAutoPasteTreatsDifferentPidWithSameBundleIdentifierAsSameTargetForFreshInsertion() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        let recordStartApp = FakeRunningApplication(
            bundleIdentifier: "com.example.TargetApp",
            processIdentifier: 1111
        )
        let pasteTimeApp = FakeRunningApplication(
            bundleIdentifier: "com.example.TargetApp",
            processIdentifier: 2222
        )
        var frontmostApp: NSRunningApplication? = recordStartApp
        state.frontmostAppProvider = { frontmostApp }
        state.pasteScheduler = { _, block in block() }
        state.targetAppActivator = { _ in }

        var captureAttempts = 0
        var insertedTexts: [String] = []
        var clipboardWrites: [String] = []
        var pasteShortcutPosted = false
        state.dictationInsertionHandlerProvider = {
            captureAttempts += 1
            guard captureAttempts > 1 else { return nil }
            return { text in
                insertedTexts.append(text)
                return true
            }
        }
        state.pasteboardWriter = { clipboardWrites.append($0) }
        state.simulatedPasteHandler = {
            pasteShortcutPosted = true
            return true
        }

        state.record()
        frontmostApp = pasteTimeApp
        state.handleEvent([
            "type": "transcription",
            "text": "same bundle target should get fresh ax",
        ])

        XCTAssertEqual(captureAttempts, 2)
        XCTAssertEqual(insertedTexts, ["same bundle target should get fresh ax"])
        XCTAssertEqual(clipboardWrites, [])
        XCTAssertFalse(pasteShortcutPosted)
    }

    func testAutoPasteFallsBackToClipboardOnlyAfterFreshAndCapturedInsertionFail() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        var frontmostApp: NSRunningApplication? = NSRunningApplication.current
        state.frontmostAppProvider = { frontmostApp }
        state.pasteScheduler = { _, block in block() }
        state.targetAppActivator = { _ in }

        var captureAttempts = 0
        var freshAttempts: [String] = []
        var capturedAttempts: [String] = []
        var clipboardWrites: [String] = []
        var pasteboardString: String?
        var pasteShortcutPosted = false
        state.dictationInsertionHandlerProvider = {
            captureAttempts += 1
            if captureAttempts == 1 {
                return { text in
                    capturedAttempts.append(text)
                    return false
                }
            }
            return { text in
                freshAttempts.append(text)
                return false
            }
        }
        state.pasteboardWriter = {
            clipboardWrites.append($0)
            pasteboardString = $0
        }
        state.pasteboardStringProvider = { pasteboardString }
        state.simulatedPasteHandler = {
            pasteShortcutPosted = true
            return true
        }

        state.record()
        frontmostApp = nil
        state.handleEvent([
            "type": "transcription",
            "text": "clipboard only after ax misses",
        ])

        XCTAssertEqual(captureAttempts, 2)
        XCTAssertEqual(freshAttempts, ["clipboard only after ax misses"])
        XCTAssertEqual(capturedAttempts, ["clipboard only after ax misses"])
        XCTAssertEqual(clipboardWrites, ["clipboard only after ax misses"])
        XCTAssertTrue(pasteShortcutPosted)
    }

    func testAutoPasteAttemptsFreshInsertionAfterActivatingRecordedTarget() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        var frontmostApp: NSRunningApplication? = NSRunningApplication.current
        state.frontmostAppProvider = { frontmostApp }
        state.pasteScheduler = { _, block in block() }
        state.targetAppActivator = { _ in
            frontmostApp = NSRunningApplication.current
        }

        var captureAttempts = 0
        var staleCapturedTexts: [String] = []
        var freshFocusedTexts: [String] = []
        var clipboardWrites: [String] = []
        var pasteShortcutPosted = false
        state.dictationInsertionHandlerProvider = {
            captureAttempts += 1
            if captureAttempts == 1 {
                return { text in
                    staleCapturedTexts.append(text)
                    return true
                }
            }
            return { text in
                freshFocusedTexts.append(text)
                return true
            }
        }
        state.pasteboardWriter = { clipboardWrites.append($0) }
        state.simulatedPasteHandler = {
            pasteShortcutPosted = true
            return true
        }

        state.record()
        frontmostApp = nil
        state.handleEvent([
            "type": "transcription",
            "text": "paste into target after activation",
        ])

        XCTAssertEqual(captureAttempts, 2)
        XCTAssertEqual(staleCapturedTexts, [])
        XCTAssertEqual(freshFocusedTexts, ["paste into target after activation"])
        XCTAssertEqual(clipboardWrites, [])
        XCTAssertFalse(pasteShortcutPosted)
    }

    func testAutoPasteAttemptsFreshInsertionCaptureBeforeClipboardFallback() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        state.frontmostAppProvider = { NSRunningApplication.current }
        state.pasteScheduler = { _, block in block() }
        state.targetAppActivator = { _ in }

        var captureAttempts = 0
        var insertedTexts: [String] = []
        var clipboardWrites: [String] = []
        var pasteShortcutPosted = false
        state.dictationInsertionHandlerProvider = {
            captureAttempts += 1
            guard captureAttempts > 1 else { return nil }
            return { text in
                insertedTexts.append(text)
                return true
            }
        }
        state.pasteboardWriter = { clipboardWrites.append($0) }
        state.simulatedPasteHandler = {
            pasteShortcutPosted = true
            return true
        }

        state.record()
        state.handleEvent([
            "type": "transcription",
            "text": "fresh capture should insert here",
        ])

        XCTAssertEqual(captureAttempts, 2)
        XCTAssertEqual(insertedTexts, ["fresh capture should insert here"])
        XCTAssertEqual(clipboardWrites, [])
        XCTAssertFalse(pasteShortcutPosted)
    }

    func testAutoPasteFallsBackToClipboardWhenRecordedInputInsertionFails() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        var frontmostApp: NSRunningApplication? = NSRunningApplication.current
        state.frontmostAppProvider = { frontmostApp }
        state.pasteScheduler = { _, block in block() }
        state.targetAppActivator = { _ in }

        var insertedTexts: [String] = []
        var clipboardWrites: [String] = []
        var restoredSnapshots: [PasteboardSnapshot] = []
        var pasteboardString: String?
        var pasteShortcutPosted = false
        var pasteboardChangeCount = 7
        state.dictationInsertionHandlerProvider = {
            { text in
                insertedTexts.append(text)
                return false
            }
        }
        state.pasteboardSnapshotter = {
            PasteboardSnapshot(
                changeCount: pasteboardChangeCount,
                items: [["public.utf8-plain-text": Data("user-copy".utf8)]]
            )
        }
        state.pasteboardWriter = {
            clipboardWrites.append($0)
            pasteboardString = $0
            pasteboardChangeCount += 1
        }
        state.pasteboardStringProvider = { pasteboardString }
        state.pasteboardChangeCountProvider = { pasteboardChangeCount }
        state.pasteboardSnapshotRestorer = {
            restoredSnapshots.append($0)
            pasteboardChangeCount += 1
        }
        state.simulatedPasteHandler = {
            pasteShortcutPosted = true
            return true
        }

        state.record()
        frontmostApp = nil
        state.handleEvent([
            "type": "transcription",
            "text": "this is the full transcript ending with wow",
        ])

        XCTAssertEqual(insertedTexts, [
            "this is the full transcript ending with wow",
            "this is the full transcript ending with wow",
        ])
        XCTAssertEqual(clipboardWrites, ["this is the full transcript ending with wow"])
        XCTAssertEqual(restoredSnapshots, [
            PasteboardSnapshot(
                changeCount: 7,
                items: [["public.utf8-plain-text": Data("user-copy".utf8)]]
            ),
        ])
        XCTAssertTrue(pasteShortcutPosted)
        XCTAssertEqual(state.confirmationText, "this is the full transcript ending with wow")
    }

    func testAutoPasteShowsSuccessTranscriptWhenNoFocusedInputWasCaptured() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        state.frontmostAppProvider = { NSRunningApplication.current }
        state.pasteScheduler = { _, block in block() }
        state.targetAppActivator = { _ in }
        state.dictationInsertionHandlerProvider = { nil }
        var pasteboardString: String?
        state.pasteboardWriter = { pasteboardString = $0 }
        state.pasteboardStringProvider = { pasteboardString }
        state.simulatedPasteHandler = { true }

        state.record()
        state.handleEvent([
            "type": "transcription",
            "text": "this might not have an input",
        ])

        XCTAssertEqual(state.confirmationText, "this might not have an input")
    }

    func testAutoPasteDoesNotPostPasteShortcutWhenPasteboardWriteDoesNotLoadTranscript() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        state.frontmostAppProvider = { NSRunningApplication.current }
        state.pasteScheduler = { _, block in block() }
        state.targetAppActivator = { _ in }
        state.dictationInsertionHandlerProvider = { nil }
        state.pasteboardSnapshotter = { nil }

        var clipboardWrites: [String] = []
        var controlLayerEvents: [(String, [String: String])] = []
        var pasteShortcutPosted = false
        state.pasteboardWriter = { clipboardWrites.append($0) }
        state.pasteboardStringProvider = {
            "stale clipboard content that must not be pasted"
        }
        state.controlLayerEventWriter = { event, details in
            controlLayerEvents.append((event, details))
        }
        state.simulatedPasteHandler = {
            pasteShortcutPosted = true
            return true
        }

        state.record()
        state.handleEvent([
            "type": "transcription",
            "text": "fresh transcript that must not paste stale clipboard content",
        ])

        XCTAssertEqual(clipboardWrites, ["fresh transcript that must not paste stale clipboard content"])
        XCTAssertFalse(pasteShortcutPosted)
        XCTAssertEqual(state.confirmationText, "Paste failed — click input and press Shift+F5")
        XCTAssertTrue(controlLayerEvents.contains { event, details in
            event == "paste_clipboard_write_failed" &&
                details["expectedTextLength"] == "60" &&
                details["pasteboardTextLength"] == "47"
        })
    }

    func testAutoPasteSkipsClipboardRestoreIfClipboardChangesDuringFallbackPaste() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        var frontmostApp: NSRunningApplication? = NSRunningApplication.current
        state.frontmostAppProvider = { frontmostApp }
        state.targetAppActivator = { _ in }

        var insertedTexts: [String] = []
        var clipboardWrites: [String] = []
        var restoredSnapshots: [PasteboardSnapshot] = []
        var pasteboardString: String?
        var pasteShortcutPosted = false
        var pasteboardChangeCount = 3

        state.dictationInsertionHandlerProvider = {
            { text in
                insertedTexts.append(text)
                return false
            }
        }
        state.pasteScheduler = { _, block in block() }
        state.pasteboardSnapshotter = {
            PasteboardSnapshot(
                changeCount: pasteboardChangeCount,
                items: [["public.utf8-plain-text": Data("user-copy".utf8)]]
            )
        }
        state.pasteboardWriter = {
            clipboardWrites.append($0)
            pasteboardString = $0
            pasteboardChangeCount += 1
        }
        state.pasteboardStringProvider = { pasteboardString }
        state.pasteboardChangeCountProvider = { pasteboardChangeCount }
        state.pasteboardSnapshotRestorer = {
            restoredSnapshots.append($0)
            pasteboardChangeCount += 1
        }
        state.simulatedPasteHandler = {
            pasteShortcutPosted = true
            pasteboardString = "new user clipboard"
            pasteboardChangeCount += 1
            return true
        }

        state.record()
        frontmostApp = nil
        state.handleEvent([
            "type": "transcription",
            "text": "clipboard safety check",
        ])

        XCTAssertEqual(insertedTexts, [
            "clipboard safety check",
            "clipboard safety check",
        ])
        XCTAssertEqual(clipboardWrites, ["clipboard safety check"])
        XCTAssertTrue(pasteShortcutPosted)
        XCTAssertEqual(restoredSnapshots, [])
        XCTAssertEqual(pasteboardString, "new user clipboard")
    }

    func testAutoPasteRestoresClipboardAfterFallbackPasteDelay() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        state.frontmostAppProvider = { NSRunningApplication.current }
        state.targetAppActivator = { _ in }
        state.pasteConfirmationDelay = 0

        var scheduled: [(delay: TimeInterval, block: () -> Void)] = []
        var pasteboardString: String?
        var pasteboardChangeCount = 5
        var restoredSnapshots: [PasteboardSnapshot] = []

        state.pasteScheduler = { delay, block in
            scheduled.append((delay, block))
        }
        state.pasteboardSnapshotter = {
            PasteboardSnapshot(
                changeCount: pasteboardChangeCount,
                items: [["public.utf8-plain-text": Data("old clipboard".utf8)]]
            )
        }
        state.pasteboardWriter = {
            pasteboardString = $0
            pasteboardChangeCount += 1
        }
        state.pasteboardStringProvider = { pasteboardString }
        state.pasteboardChangeCountProvider = { pasteboardChangeCount }
        state.pasteboardSnapshotRestorer = {
            restoredSnapshots.append($0)
            pasteboardString = "old clipboard"
            pasteboardChangeCount += 1
        }
        state.simulatedPasteHandler = { true }

        state.record()
        state.handleEvent([
            "type": "transcription",
            "text": "fresh transcript",
        ])

        XCTAssertEqual(scheduled.count, 1)
        scheduled[0].block()

        XCTAssertEqual(scheduled.count, 2)
        scheduled[1].block()

        XCTAssertEqual(pasteboardString, "fresh transcript")
        XCTAssertEqual(restoredSnapshots, [])
        XCTAssertEqual(state.confirmationText, "fresh transcript")
        XCTAssertEqual(scheduled.count, 3)
        XCTAssertEqual(scheduled[2].delay, 0.5, accuracy: 0.001)

        scheduled[2].block()

        XCTAssertEqual(pasteboardString, "old clipboard")
        XCTAssertEqual(restoredSnapshots, [
            PasteboardSnapshot(
                changeCount: 5,
                items: [["public.utf8-plain-text": Data("old clipboard".utf8)]]
            ),
        ])
        XCTAssertEqual(scheduled.count, 3)
    }

    func testDefaultFallbackPasteboardWriterMarksTranscriptAsTransientAndAutoGenerated() {
        let pasteboard = NSPasteboard.general
        let saved = Self.capturePasteboardForTest()
        defer { Self.restorePasteboardForTest(saved) }
        let state = VoiceState()

        state.pasteboardWriter("fresh transcript")

        XCTAssertEqual(pasteboard.string(forType: .string), "fresh transcript")
        XCTAssertNotNil(pasteboard.data(forType: Self.transientType))
        XCTAssertNotNil(pasteboard.data(forType: Self.autoGeneratedType))
    }

    func testDefaultPasteboardSnapshotSkipsDynamicAndNspasteboardTypes() {
        let pasteboard = NSPasteboard.general
        let saved = Self.capturePasteboardForTest()
        defer { Self.restorePasteboardForTest(saved) }
        let state = VoiceState()
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setData(Data("keep".utf8), forType: .string)
        item.setData(Data("dynamic".utf8), forType: NSPasteboard.PasteboardType("dyn.voicebar-test"))
        item.setData(Data(), forType: Self.transientType)
        item.setData(Data(), forType: Self.autoGeneratedType)
        pasteboard.writeObjects([item])

        let snapshot = state.pasteboardSnapshotter()
        let itemTypes = Set(snapshot?.items.first.map { Array($0.keys) } ?? [])

        XCTAssertTrue(itemTypes.contains(NSPasteboard.PasteboardType.string.rawValue))
        XCTAssertFalse(itemTypes.contains("dyn.voicebar-test"))
        XCTAssertFalse(itemTypes.contains(Self.transientType.rawValue))
        XCTAssertFalse(itemTypes.contains(Self.autoGeneratedType.rawValue))
    }

    func testDefaultPasteboardRestorerMarksRestoredContentAsTransientAndAutoGenerated() {
        let pasteboard = NSPasteboard.general
        let saved = Self.capturePasteboardForTest()
        defer { Self.restorePasteboardForTest(saved) }
        let state = VoiceState()

        state.pasteboardSnapshotRestorer(
            PasteboardSnapshot(
                changeCount: pasteboard.changeCount,
                items: [[NSPasteboard.PasteboardType.string.rawValue: Data("old clipboard".utf8)]]
            )
        )

        XCTAssertEqual(pasteboard.string(forType: .string), "old clipboard")
        XCTAssertNotNil(pasteboard.data(forType: Self.transientType))
        XCTAssertNotNil(pasteboard.data(forType: Self.autoGeneratedType))
    }

    func testAutoPasteFailureUsesGenericMessageInsteadOfAccessibilityBlame() {
        let state = VoiceState()
        state.sendCommand = { _ in }
        state.frontmostAppProvider = { NSRunningApplication.current }
        state.pasteScheduler = { _, block in block() }
        state.targetAppActivator = { _ in }
        state.dictationInsertionHandlerProvider = { { _ in false } }
        var pasteboardString: String?
        state.pasteboardWriter = { pasteboardString = $0 }
        state.pasteboardStringProvider = { pasteboardString }
        state.simulatedPasteHandler = { false }

        state.record()
        state.handleEvent([
            "type": "transcription",
            "text": "this is the full transcript ending with wow",
        ])

        XCTAssertEqual(state.confirmationText, "Paste failed — click input and press Shift+F5")
        XCTAssertFalse(state.confirmationText?.contains("Accessibility") ?? true)
    }

    func testRepasteWaitsForMenuFocusToSettle() {
        XCTAssertGreaterThan(VoicePastePlan.repaste.activationDelay, 0)
        XCTAssertEqual(VoicePastePlan.autoPaste.activationDelay, 0)
    }

    func testRecentTranscriptionsAreMostRecentFirst() {
        let state = VoiceState(
            recentTranscriptionsLoader: { [] },
            recentTranscriptionsSaver: { _ in }
        )

        state.handleEvent([
            "type": "transcription",
            "text": "first note",
        ])
        state.handleEvent([
            "type": "transcription",
            "text": "second note",
        ])
        state.handleEvent([
            "type": "transcription",
            "text": "third note",
        ])

        XCTAssertEqual(state.recentTranscriptions, [
            "third note",
            "second note",
            "first note",
        ])
    }

    private static func capturePasteboardForTest() -> [[String: Data]] {
        NSPasteboard.general.pasteboardItems?.map { item in
            item.types.reduce(into: [String: Data]()) { result, type in
                if let data = item.data(forType: type) {
                    result[type.rawValue] = data
                }
            }
        } ?? []
    }

    private static func restorePasteboardForTest(_ saved: [[String: Data]]) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        let items = saved.map { itemSnapshot -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in itemSnapshot {
                item.setData(data, forType: NSPasteboard.PasteboardType(type))
            }
            return item
        }
        if !items.isEmpty {
            pasteboard.writeObjects(items)
        }
    }
}
